//! Owner: VTI Test Intelligence subsystem — CI pipeline generation
//! Proof: `cargo nextest run -p jeryu -- test_intel::ci_gen`
//! Invariants: Generated CI preserves required lanes and never removes mandatory proof gates.
//! GitLab child pipeline YAML generation from a TestPlan.
//!
//! Converts a selected test plan into the minimal `.gitlab-ci.yml` for
//! a dynamic child pipeline, or a GitHub Actions matrix JSON.

use crate::test_intel::planner::{TestPlan, TestPlanMode};

/// Generate a GitLab child pipeline YAML from a test plan.
///
/// If the plan mode is `Full`, emits a single job running all tests.
/// If `Selected`, emits one job per unique (subsystem, kind) pair.
/// If `DocsOnly`, emits a no-op job.
pub fn emit_gitlab_child_yaml(plan: &TestPlan) -> String {
    match &plan.mode {
        TestPlanMode::Full => {
            format!(
                r#"# Auto-generated by jeryu Test Intelligence — full pipeline
# Reason: {}
image: rust:1.92.0

stages:
  - test

full-validation:
  stage: test
  tags:
    - build
  script:
    - cargo test --lib --tests --all-features
  artifacts:
    when: always
    reports:
      junit: target/nextest/ci/junit.xml
"#,
                plan.repair_reason.as_deref().unwrap_or("forced full")
            )
        }
        TestPlanMode::DocsOnly => "# Auto-generated by jeryu Test Intelligence — docs-only\n\
             image: rust:1.92.0\n\n\
             docs-check:\n\
             \x20 stage: test\n\
             \x20 script:\n\
             \x20   - echo 'Documentation-only change. No Rust tests required.'\n"
            .to_string(),
        TestPlanMode::Selected => {
            let mut yaml = String::from(
                "# Auto-generated by jeryu Test Intelligence — selected pipeline\n\
                 image: rust:1.92.0\n\n\
                 stages:\n\
                 \x20 - test\n\n",
            );

            for (i, test) in plan.selected_tests.iter().enumerate() {
                let job_name = format!("vti-{}-{:02}", sanitize_job_name(&test.subsystem), i);
                let tags = infer_tags(&test.subsystem);

                yaml.push_str(&format!(
                    "{job_name}:\n\
                     \x20 stage: test\n\
                     \x20 tags:\n\
                     {tags}\
                     \x20 script:\n\
                     \x20   - {command}\n\
                     \x20 artifacts:\n\
                     \x20   when: always\n\
                     \x20   reports:\n\
                     \x20     junit: target/nextest/ci/junit.xml\n\n",
                    job_name = job_name,
                    tags = tags,
                    command = test.command,
                ));
            }

            // Add sentinel tests if any
            for (i, test) in plan.sentinel_tests.iter().enumerate() {
                yaml.push_str(&format!(
                    "vti-sentinel-{:02}:\n\
                     \x20 stage: test\n\
                     \x20 allow_failure: true\n\
                     \x20 tags:\n\
                     \x20   - default\n\
                     \x20 script:\n\
                     \x20   - {command}\n\n",
                    i,
                    command = test.command,
                ));
            }

            yaml
        }
    }
}

/// Generate a GitHub Actions job matrix from a test plan.
pub fn emit_github_matrix(plan: &TestPlan) -> serde_json::Value {
    match &plan.mode {
        TestPlanMode::Full => serde_json::json!({
            "include": [{
                "name": "full-validation",
                "command": "cargo test --lib --tests --all-features"
            }]
        }),
        TestPlanMode::DocsOnly => serde_json::json!({
            "include": []
        }),
        TestPlanMode::Selected => {
            let items: Vec<_> = plan
                .selected_tests
                .iter()
                .map(|t| {
                    serde_json::json!({
                        "name": format!("{}-{}", t.subsystem, t.kind),
                        "command": t.command,
                        "subsystem": t.subsystem
                    })
                })
                .collect();
            serde_json::json!({ "include": items })
        }
    }
}

fn sanitize_job_name(name: &str) -> String {
    name.replace(|c: char| !c.is_alphanumeric() && c != '-', "-")
        .to_lowercase()
}

fn infer_tags(subsystem: &str) -> String {
    let tags = match subsystem {
        "pool" | "exec" => vec!["build", "docker-build"],
        _ => vec!["default", "rust", "test"],
    };
    tags.iter().map(|t| format!("    - {}\n", t)).collect()
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::test_intel::planner;

    #[test]
    fn full_plan_produces_single_job() {
        let plan = TestPlan::full("test reason");
        let yaml = emit_gitlab_child_yaml(&plan);
        assert!(yaml.contains("full-validation:"));
        assert!(yaml.contains("cargo test --lib --tests"));
        assert!(yaml.contains("test reason"));
    }

    #[test]
    fn docs_plan_produces_no_op() {
        let plan = TestPlan::docs_only();
        let yaml = emit_gitlab_child_yaml(&plan);
        assert!(yaml.contains("docs-check:"));
        assert!(yaml.contains("No Rust tests required"));
    }

    #[test]
    fn selected_plan_produces_multiple_jobs() {
        let plan = planner::plan_tests(&["src/pool.rs".to_string()]);
        let yaml = emit_gitlab_child_yaml(&plan);
        assert!(yaml.contains("vti-pool-"));
        assert!(yaml.contains("cargo nextest run"));
        // Should have build tags for pool
        assert!(yaml.contains("docker-build"));
    }

    #[test]
    fn tui_plan_uses_default_tags() {
        let plan = planner::plan_tests(&["src/tui/ui.rs".to_string()]);
        let yaml = emit_gitlab_child_yaml(&plan);
        assert!(yaml.contains("default"));
        assert!(!yaml.contains("docker-build"));
    }

    #[test]
    fn github_matrix_full() {
        let plan = TestPlan::full("reason");
        let matrix = emit_github_matrix(&plan);
        let includes = matrix["include"].as_array().unwrap();
        assert_eq!(includes.len(), 1);
        assert!(
            includes[0]["command"]
                .as_str()
                .unwrap()
                .contains("cargo test")
        );
    }

    #[test]
    fn github_matrix_selected() {
        let plan = planner::plan_tests(&["src/decision.rs".to_string()]);
        let matrix = emit_github_matrix(&plan);
        let includes = matrix["include"].as_array().unwrap();
        assert!(!includes.is_empty());
        assert!(includes.iter().any(|item| item["subsystem"] == "decision"));
    }
}
