use super::*;

#[path = "app_runtime_demo_fixtures.rs"]
mod fixtures;
use fixtures::*;

pub(crate) fn build_demo_state(
    now: chrono::DateTime<chrono::Utc>,
    now_str: String,
    flow_jobs: Vec<JobEvent>,
    flow: crate::tui::flow::FlowSnapshot,
    release_status: release::ReleaseAttemptView,
    progress_pct: u16,
) -> TuiStateSnapshot {
    TuiStateSnapshot {
        pools: vec![
            Pool {
                name: "trusted".into(),
                gitlab_runner_id: 9001,
                auth_token: "token-trusted".into(),
                tags: "linux,x86_64,trusted".into(),
                executor: "docker".into(),
                min_warm: 2,
                max_managers: 10,
                concurrent: 4,
                request_concurrency: 4,
                paused: false,
                trust_tier: "trusted".into(),
            },
            Pool {
                name: "security".into(),
                gitlab_runner_id: 9002,
                auth_token: "token-security".into(),
                tags: "linux,x86_64,security".into(),
                executor: "docker".into(),
                min_warm: 1,
                max_managers: 4,
                concurrent: 2,
                request_concurrency: 2,
                paused: false,
                trust_tier: "restricted".into(),
            },
        ],
        gitlab_ready: true,
        active_containers: 11,
        recent_jobs: flow_jobs,
        pipelines: vec![
            PipelineMetrics {
                pipeline: demo_pipeline(8_013, "running", now_str.clone()),
                total: 5,
                completed: 2,
            },
            PipelineMetrics {
                pipeline: demo_pipeline(8_014, "pending", now_str.clone()),
                total: 3,
                completed: 0,
            },
        ],
        flow,
        live_log: LiveLogState {
            target: Some(LogTarget {
                project_id: release::DEFAULT_RELEASE_PROJECT_ID,
                job_id: 9_002,
            }),
            text: "[demo] security gate failed due to outdated artifact cache\n[demo] remediation required with clean cache namespace\n".into(),
            updated_at: Some(now_str.clone()),
            error: None,
            outdated: false,
        },
        hot_cache_usage_bytes: 2_340_000_000,
        cache_hits: 1_102,
        cache_objects_count: 2_900,
        proxy_healthy: true,
        registry_healthy: true,
        mirror_enabled: true,
        ca_mounted: true,
        singleflight_requests: 72,
        hit_ratio: 0.88,
        miss_count: 148,
        total_requests: 1_250,
        active_taint_count: 1,
        detonation_breaches: 0,
        cold_execution_downgrades: 0,
        cas_disk_bytes: 11_500_000,
        crate_cache_disk_bytes: 8_900_000,
        storage_breakdown: StorageBreakdown {
            docker_images_bytes: 7_000_000,
            docker_volumes_bytes: 3_000_000,
            docker_build_cache_bytes: 5_000_000,
            cas_bytes: 11_500_000,
            crate_cache_bytes: 8_900_000,
            runner_data_bytes: 2_600_000,
            git_repos_bytes: 1_200_000,
            rust_target_bytes: 2_300_000,
            state_store_bytes: 450_000,
            total_disk_bytes: 45_000_000,
            disk_available_bytes: 120_000_000,
        },
        pipeline_eta: Some("~6m".into()),
        pipeline_progress: progress_pct,
        release_status: Some(release_status.clone()),
        release_status_generated_at: Some(now_str.clone()),
        test_bottlenecks_avg: vec![
            crate::state::TestBottleneck {
                test_name: "integration::cache_warmer_info_routes_to_all_and_cache".into(),
                avg_duration_ms: 7_200.0,
                latest_duration_ms: 7_450,
                count: 12,
            },
            crate::state::TestBottleneck {
                test_name: "unit::signal_processing".into(),
                avg_duration_ms: 1_100.0,
                latest_duration_ms: 1_020,
                count: 24,
            },
            crate::state::TestBottleneck {
                test_name: "integration::large_batch_completes_under_10ms".into(),
                avg_duration_ms: 18_000.0,
                latest_duration_ms: 18_720,
                count: 4,
            },
        ],
        test_bottlenecks_latest: vec![
            crate::state::TestBottleneck {
                test_name: "integration::large_batch_completes_under_10ms".into(),
                avg_duration_ms: 18_000.0,
                latest_duration_ms: 18_720,
                count: 4,
            },
            crate::state::TestBottleneck {
                test_name: "integration::auth_error_routes_to_alerts_and_security".into(),
                avg_duration_ms: 5_300.0,
                latest_duration_ms: 5_910,
                count: 9,
            },
            crate::state::TestBottleneck {
                test_name: "unit::malformed_signal_drops".into(),
                avg_duration_ms: 6_200.0,
                latest_duration_ms: 6_000,
                count: 6,
            },
        ],
        last_sync_at: Some(now),
        inspector_capsule: Some(crate::capsule::FailureCapsule {
            job_id: 9_004,
            pipeline_id: Some(8_013),
            project_id: release::DEFAULT_RELEASE_PROJECT_ID,
            stage: "security".into(),
            exit_code: 1,
            commit_sha: "9c3f2d4e0b9f5d1d7cc8".into(),
            ref_name: "main".into(),
            working_directory: "/workspace".into(),
            log_snippet: "security gate timed out in artifact verification".into(),
            repro_script: "./tools/run-security-gate.sh".into(),
            environment: std::collections::HashMap::new(),
            failure_kind: "timeout".into(),
            summary: "security gate timeout on canary validation".into(),
            superseded_by_sha: None,
            requeued_from_job_id: None,
        }),
        inspector_job_id: Some(9_004),
        recent_evidence: vec![
            demo_evidence_record(
                11,
                "vti_validation",
                9_003,
                "test",
                "ok",
                "{\"scope\": \"tests\", \"cache\": \"hit\"}",
                now_str.clone(),
            ),
            demo_evidence_record(
                12,
                "secret_audit",
                9_001,
                "prepare",
                "compliant",
                "{\"vault\": \"rotation_ok\"}",
                now_str.clone(),
            ),
        ],
        secret_audit_events: vec![
            demo_secret_audit_event(
                21,
                "release",
                "rotated",
                "release token rotated for canary context",
                now_str.clone(),
            ),
            demo_secret_audit_event(
                22,
                "agent",
                "fetched",
                "agent bootstrap secret requested",
                now_str.clone(),
            ),
        ],
        agent_pipelines: vec![
            demo_pipeline(8_013, "running", now_str.clone()),
            TrackedPipeline {
                pipeline_id: 8_014,
                project_id: release::DEFAULT_RELEASE_PROJECT_ID,
                ref_name: "agent/repair-hypothesis".into(),
                sha: "e8f2d2b77a11".into(),
                status: "success".into(),
                updated_at: now_str.clone(),
            },
        ],
        recent_audit_events: vec![
            crate::state::EventLog {
                id: 501,
                event_type: "capability.granted".into(),
                timestamp: now_str.clone(),
                project_id: Some(release::DEFAULT_RELEASE_PROJECT_ID),
                job_id: Some(9_001),
                actor: "ci-bot".into(),
                payload: "{\"action\": \"run_validation\"}".into(),
            },
            crate::state::EventLog {
                id: 502,
                event_type: "vti.receipt".into(),
                timestamp: now_str.clone(),
                project_id: Some(release::DEFAULT_RELEASE_PROJECT_ID),
                job_id: Some(9_003),
                actor: "validator".into(),
                payload: "{\"status\": \"selected\", \"selector\": \"safe\"}".into(),
            },
            crate::state::EventLog {
                id: 503,
                event_type: "merge_gate.blocked".into(),
                timestamp: now_str.clone(),
                project_id: Some(release::DEFAULT_RELEASE_PROJECT_ID),
                job_id: Some(9_004),
                actor: "gatekeeper".into(),
                payload: "{\"reason\": \"security_gate_failed\"}".into(),
            },
        ],
        recent_git_events: vec![],
        runner_feeds: demo_runner_feeds(&now_str),
        active_feed_index: 0,
        feed_cycle_tick: 0,
        feed_auto_cycle: true,
        pipeline_progress_view: Some(demo_pipeline_progress_view(&now_str)),
        event_ticker_offset: 0,
        release_stages: demo_release_stages(),
        approvals_queue: demo_approvals_queue(),
        agent_connected: true, // demo is "connected"
    }
}
