use super::*;

pub(crate) fn build_demo_state(
    now: chrono::DateTime<chrono::Utc>,
    now_str: String,
    flow_jobs: Vec<JobEvent>,
    flow: crate::tui::flow::FlowSnapshot,
    release_status: release::ReleaseAttemptView,
    progress_pct: u16,
) -> TuiStateSnapshot {
    TuiStateSnapshot {
        pools: vec![
            Pool {
                name: "trusted".into(),
                gitlab_runner_id: 9001,
                auth_token: "token-trusted".into(),
                tags: "linux,x86_64,trusted".into(),
                executor: "docker".into(),
                min_warm: 2,
                max_managers: 10,
                concurrent: 4,
                request_concurrency: 4,
                paused: false,
                trust_tier: "trusted".into(),
            },
            Pool {
                name: "security".into(),
                gitlab_runner_id: 9002,
                auth_token: "token-security".into(),
                tags: "linux,x86_64,security".into(),
                executor: "docker".into(),
                min_warm: 1,
                max_managers: 4,
                concurrent: 2,
                request_concurrency: 2,
                paused: false,
                trust_tier: "restricted".into(),
            },
        ],
        gitlab_ready: true,
        active_containers: 11,
        recent_jobs: flow_jobs,
        pipelines: vec![
            PipelineMetrics {
                pipeline: demo_pipeline(8_013, "running", now_str.clone()),
                total: 5,
                completed: 2,
            },
            PipelineMetrics {
                pipeline: demo_pipeline(8_014, "pending", now_str.clone()),
                total: 3,
                completed: 0,
            },
        ],
        flow,
        live_log: LiveLogState {
            target: Some(LogTarget {
                project_id: release::DEFAULT_RELEASE_PROJECT_ID,
                job_id: 9_002,
            }),
            text: "[demo] security gate failed due to outdated artifact cache\n[demo] remediation required with clean cache namespace\n".into(),
            updated_at: Some(now_str.clone()),
            error: None,
            outdated: false,
        },
        jankurai: demo_jankurai_snapshot(now),
        hot_cache_usage_bytes: 2_340_000_000,
        cache_hits: 1_102,
        cache_objects_count: 2_900,
        proxy_healthy: true,
        registry_healthy: true,
        mirror_enabled: true,
        ca_mounted: true,
        singleflight_requests: 72,
        hit_ratio: 0.88,
        miss_count: 148,
        total_requests: 1_250,
        active_taint_count: 1,
        detonation_breaches: 0,
        cold_execution_downgrades: 0,
        cas_disk_bytes: 11_500_000,
        crate_cache_disk_bytes: 8_900_000,
        storage_breakdown: StorageBreakdown {
            docker_images_bytes: 7_000_000,
            docker_volumes_bytes: 3_000_000,
            docker_build_cache_bytes: 5_000_000,
            cas_bytes: 11_500_000,
            crate_cache_bytes: 8_900_000,
            runner_data_bytes: 2_600_000,
            git_repos_bytes: 1_200_000,
            rust_target_bytes: 2_300_000,
            state_store_bytes: 450_000,
            total_disk_bytes: 45_000_000,
            disk_available_bytes: 120_000_000,
        },
        pipeline_eta: Some("~6m".into()),
        pipeline_progress: progress_pct,
        release_status: Some(release_status.clone()),
        release_status_generated_at: Some(now_str.clone()),
        test_bottlenecks_avg: vec![
            crate::state::TestBottleneck {
                test_name: "integration::cache_warmer_info_routes_to_all_and_cache".into(),
                avg_duration_ms: 7_200.0,
                latest_duration_ms: 7_450,
                count: 12,
            },
            crate::state::TestBottleneck {
                test_name: "unit::signal_processing".into(),
                avg_duration_ms: 1_100.0,
                latest_duration_ms: 1_020,
                count: 24,
            },
            crate::state::TestBottleneck {
                test_name: "integration::large_batch_completes_under_10ms".into(),
                avg_duration_ms: 18_000.0,
                latest_duration_ms: 18_720,
                count: 4,
            },
        ],
        test_bottlenecks_latest: vec![
            crate::state::TestBottleneck {
                test_name: "integration::large_batch_completes_under_10ms".into(),
                avg_duration_ms: 18_000.0,
                latest_duration_ms: 18_720,
                count: 4,
            },
            crate::state::TestBottleneck {
                test_name: "integration::auth_error_routes_to_alerts_and_security".into(),
                avg_duration_ms: 5_300.0,
                latest_duration_ms: 5_910,
                count: 9,
            },
            crate::state::TestBottleneck {
                test_name: "unit::malformed_signal_drops".into(),
                avg_duration_ms: 6_200.0,
                latest_duration_ms: 6_000,
                count: 6,
            },
        ],
        last_sync_at: Some(now),
        inspector_capsule: Some(crate::capsule::FailureCapsule {
            job_id: 9_004,
            pipeline_id: Some(8_013),
            project_id: release::DEFAULT_RELEASE_PROJECT_ID,
            stage: "security".into(),
            exit_code: 1,
            commit_sha: "9c3f2d4e0b9f5d1d7cc8".into(),
            ref_name: "main".into(),
            working_directory: "/workspace".into(),
            log_snippet: "security gate timed out in artifact verification".into(),
            repro_script: "./tools/run-security-gate.sh".into(),
            environment: std::collections::HashMap::new(),
            failure_kind: "timeout".into(),
            summary: "security gate timeout on canary validation".into(),
            superseded_by_sha: None,
            requeued_from_job_id: None,
        }),
        inspector_job_id: Some(9_004),
        recent_evidence: vec![
            demo_evidence_record(
                11,
                "vti_validation",
                9_003,
                "test",
                "ok",
                "{\"scope\": \"tests\", \"cache\": \"hit\"}",
                now_str.clone(),
            ),
            demo_evidence_record(
                12,
                "secret_audit",
                9_001,
                "prepare",
                "compliant",
                "{\"vault\": \"rotation_ok\"}",
                now_str.clone(),
            ),
        ],
        secret_audit_events: vec![
            demo_secret_audit_event(
                21,
                "release",
                "rotated",
                "release token rotated for canary context",
                now_str.clone(),
            ),
            demo_secret_audit_event(
                22,
                "agent",
                "fetched",
                "agent bootstrap secret requested",
                now_str.clone(),
            ),
        ],
        agent_pipelines: vec![
            demo_pipeline(8_013, "running", now_str.clone()),
            TrackedPipeline {
                pipeline_id: 8_014,
                project_id: release::DEFAULT_RELEASE_PROJECT_ID,
                ref_name: "agent/repair-hypothesis".into(),
                sha: "e8f2d2b77a11".into(),
                status: "success".into(),
                updated_at: now_str.clone(),
            },
        ],
        recent_audit_events: vec![
            crate::state::EventLog {
                id: 501,
                event_type: "capability.granted".into(),
                timestamp: now_str.clone(),
                project_id: Some(release::DEFAULT_RELEASE_PROJECT_ID),
                job_id: Some(9_001),
                actor: "ci-bot".into(),
                payload: "{\"action\": \"run_validation\"}".into(),
            },
            crate::state::EventLog {
                id: 502,
                event_type: "vti.receipt".into(),
                timestamp: now_str.clone(),
                project_id: Some(release::DEFAULT_RELEASE_PROJECT_ID),
                job_id: Some(9_003),
                actor: "validator".into(),
                payload: "{\"status\": \"selected\", \"selector\": \"safe\"}".into(),
            },
            crate::state::EventLog {
                id: 503,
                event_type: "merge_gate.blocked".into(),
                timestamp: now_str.clone(),
                project_id: Some(release::DEFAULT_RELEASE_PROJECT_ID),
                job_id: Some(9_004),
                actor: "gatekeeper".into(),
                payload: "{\"reason\": \"security_gate_failed\"}".into(),
            },
        ],
        recent_git_events: vec![],
        runner_feeds: vec![
            RunnerFeed {
                runner_name: "trusted-01".into(),
                job_id: 9_002,
                job_name: "build-image".into(),
                pipeline_id: 8_013,
                status: "running".into(),
                elapsed_secs: 134.0,
                log_tail: "[2026-05-02 23:04:12] Compiling signal-router v0.4.2\n[2026-05-02 23:04:13] Compiling tokio v1.40\n[2026-05-02 23:04:14]   warning: missing import `std::io`\n[2026-05-02 23:04:15] Compiling serde v1.0\n[2026-05-02 23:04:16] Compiling log v0.4\n[2026-05-02 23:04:17] Finished `release` profile in 2m14s".into(),
                updated_at: now_str.clone(),
            },
            RunnerFeed {
                runner_name: "trusted-02".into(),
                job_id: 9_005,
                job_name: "integration-tests".into(),
                pipeline_id: 8_013,
                status: "running".into(),
                elapsed_secs: 87.0,
                log_tail: "[2026-05-02 23:04:30] Running integration test suite...\n[2026-05-02 23:04:31] test integration::cache_warmer_info_routes_to_all_and_cache ... ok\n[2026-05-02 23:04:32] test integration::auth_error_routes_to_alerts_and_security ... FAILED\n[2026-05-02 23:04:33]   Error: route mismatch on severity filter\n[2026-05-02 23:04:34] test integration::batch_routing_preserves_signal_count ... ok".into(),
                updated_at: now_str.clone(),
            },
            RunnerFeed {
                runner_name: "security-01".into(),
                job_id: 9_004,
                job_name: "security-gate".into(),
                pipeline_id: 8_013,
                status: "failed".into(),
                elapsed_secs: 45.0,
                log_tail: "[2026-05-02 23:03:50] Running security scan...\n[2026-05-02 23:03:52] Checking artifact signatures...\n[2026-05-02 23:03:55] ERROR: Artifact verification timed out\n[2026-05-02 23:03:55] FATAL: security gate failed".into(),
                updated_at: now_str.clone(),
            },
        ],
        active_feed_index: 0,
        feed_cycle_tick: 0,
        feed_auto_cycle: true,
        pipeline_progress_view: Some(PipelineProgressView {
            pipeline_id: 8_013,
            ref_name: "main".into(),
            sha_short: "9c3f2d4e".into(),
            stages: vec![
                StageProgress {
                    stage_name: "build".into(),
                    total_jobs: 2, completed_jobs: 2, running_jobs: 0, failed_jobs: 0,
                    status: "success".into(),
                    avg_duration_secs: Some(180.0), elapsed_secs: Some(134.0),
                },
                StageProgress {
                    stage_name: "test".into(),
                    total_jobs: 3, completed_jobs: 1, running_jobs: 1, failed_jobs: 0,
                    status: "running".into(),
                    avg_duration_secs: Some(300.0), elapsed_secs: Some(87.0),
                },
                StageProgress {
                    stage_name: "security".into(),
                    total_jobs: 2, completed_jobs: 0, running_jobs: 0, failed_jobs: 1,
                    status: "failed".into(),
                    avg_duration_secs: Some(60.0), elapsed_secs: Some(45.0),
                },
                StageProgress {
                    stage_name: "deploy".into(),
                    total_jobs: 1, completed_jobs: 0, running_jobs: 0, failed_jobs: 0,
                    status: "pending".into(),
                    avg_duration_secs: Some(120.0), elapsed_secs: None,
                },
                StageProgress {
                    stage_name: "e2e".into(),
                    total_jobs: 2, completed_jobs: 0, running_jobs: 1, failed_jobs: 0,
                    status: "running".into(),
                    avg_duration_secs: Some(240.0), elapsed_secs: Some(87.0),
                },
            ],
            overall_pct: 47,
            eta_remaining_secs: Some(492),
            eta_confidence: "medium".into(),
            wall_clock_secs: 862,
            started_at: Some(now_str.clone()),
        }),
        event_ticker_offset: 0,
    }
}

fn demo_jankurai_snapshot(now: chrono::DateTime<chrono::Utc>) -> crate::tui::jankurai::JankuraiSnapshot {
    use crate::tui::jankurai::{
        JankuraiDimension, JankuraiEntry, JankuraiEntryKind, JankuraiHistoryPoint, JankuraiScan,
        JankuraiSnapshot,
    };
    
    let hist1 = now - chrono::Duration::hours(48);
    let hist2 = now - chrono::Duration::hours(24);
    let hist3 = now;

    JankuraiSnapshot {
        installed: true,
        history: vec![
            JankuraiHistoryPoint {
                generated_at: hist1,
                score: 85,
                raw_score: Some(85),
                decision: Some("advisory".into()),
            },
            JankuraiHistoryPoint {
                generated_at: hist2,
                score: 92,
                raw_score: Some(92),
                decision: Some("pass".into()),
            },
            JankuraiHistoryPoint {
                generated_at: hist3,
                score: 95,
                raw_score: Some(95),
                decision: Some("pass".into()),
            },
        ],
        dimensions: vec![
            JankuraiDimension {
                name: "Agent Capability".into(),
                weight: 40,
                score: 100,
                weighted_points: 40.0,
                evidence: vec!["all required caps enabled".into()],
                notes: vec![],
            },
            JankuraiDimension {
                name: "Testing Coverage".into(),
                weight: 30,
                score: 90,
                weighted_points: 27.0,
                evidence: vec!["missing e2e coverage".into()],
                notes: vec![],
            },
            JankuraiDimension {
                name: "Documentation".into(),
                weight: 30,
                score: 93,
                weighted_points: 28.0,
                evidence: vec!["JANKURAI_STANDARD.md exists".into()],
                notes: vec![],
            },
        ],
        entries: vec![
            JankuraiEntry {
                kind: JankuraiEntryKind::Cap,
                label: "cap-agent-execution".into(),
                severity: None,
                hardness: None,
                path: None,
                rule: None,
                lane: None,
                owner: None,
                problem: None,
                evidence: vec!["applied in JANKURAI_STANDARD.md".into()],
                suggested_fix: None,
            },
            JankuraiEntry {
                kind: JankuraiEntryKind::Finding,
                label: "rule-missing-e2e".into(),
                severity: Some("medium".into()),
                hardness: Some("soft".into()),
                path: Some("tests/e2e/".into()),
                rule: Some("REQ-TEST-E2E".into()),
                lane: Some("slow".into()),
                owner: Some("qa".into()),
                problem: Some("E2E tests not found".into()),
                evidence: vec!["no tests matched in tests/e2e/".into()],
                suggested_fix: Some("Add at least one E2E test".into()),
            },
        ],
        last_scan: Some(JankuraiScan {
            generated_at: Some(now),
            score: 95,
            raw_score: 95,
            minimum_score: 90,
            decision: "pass".into(),
            score_status: "passing".into(),
            finding_count: 1,
            hard_findings: 0,
            soft_findings: 1,
            caps_applied: vec!["cap-agent-execution".into(), "cap-secure-build".into()],
        }),
        error: None,
    }
}

