mod mirror_update_fixture;

use mirror_update_fixture::{Fixture, git, output_text, tag_snapshot};
use serde_json::{Value, json};
use std::{fs, process::Output};

fn refused(output: Output, reason: &str) {
    assert_eq!(output.status.code(), Some(1));
    assert!(output.stdout.is_empty());
    assert!(
        String::from_utf8_lossy(&output.stderr).contains(reason),
        "{}",
        String::from_utf8_lossy(&output.stderr)
    );
}

#[test]
fn initial_preparation_is_deterministic_and_preserves_existing_history_and_tags() {
    let f = Fixture::new(true);
    let tree = f.export();
    let before_source = git(&f.root, &["show-ref"]);
    let before_mirror = git(&f.mirror, &["show-ref"]);
    let first = output_text(f.prepare(&tree, Some(&f.tip)));
    git(&f.root, &["config", "i18n.commitEncoding", "ISO-8859-1"]);
    git(&f.root, &["config", "log.showSignature", "true"]);
    let second = output_text(f.prepare(&tree, Some(&f.tip)));
    assert_eq!(first, second);
    let value: Value = serde_json::from_str(&first).unwrap();
    let commit = value["prepared_commit"].as_str().unwrap();
    assert_eq!(git(&f.root, &["show", "-s", "--format=%P", commit]), f.tip);
    assert_eq!(
        git(&f.root, &["rev-parse", &format!("{commit}^{{tree}}")]),
        tree
    );
    assert_eq!(
        value["generator_source_blobs"].as_object().unwrap().len(),
        7
    );
    assert_eq!(value["publication_qualified"], false);
    assert_eq!(value["qualification_verified"], false);
    assert_eq!(value["no_op"], false);
    assert_eq!(git(&f.root, &["show-ref"]), before_source);
    assert_eq!(git(&f.mirror, &["show-ref"]), before_mirror);
    assert_eq!(
        fs::read_to_string(&f.tags).unwrap(),
        tag_snapshot(&f.mirror)
    );
    assert!(git(&f.root, &["status", "--porcelain"]).is_empty());
}

#[test]
fn legacy_transition_and_missing_parent_require_explicit_inputs() {
    let f = Fixture::new(true);
    let tree = f.export();
    refused(f.prepare(&tree, None), "explicit matching --initial-tip");
    refused(
        f.prepare(&tree, Some(&f.source)),
        "explicit matching --initial-tip",
    );
    let missing = Fixture::new(false);
    refused(
        missing.prepare(&missing.export(), Some(&missing.tip)),
        "offline mirror Git operation failed: cat-file",
    );
}

#[test]
fn changed_expected_tags_or_main_tip_refuse_preparation() {
    let f = Fixture::new(true);
    let tree = f.export();
    git(&f.mirror, &["tag", "unexpected", &f.tip]);
    refused(
        f.prepare(&tree, Some(&f.tip)),
        "expected mirror tags changed",
    );
    fs::write(&f.tags, tag_snapshot(&f.mirror)).unwrap();
    let next = git(
        &f.mirror,
        &[
            "commit-tree",
            &git(&f.mirror, &["rev-parse", "HEAD^{tree}"]),
            "-p",
            &f.tip,
            "-m",
            "Concurrent mirror update",
        ],
    );
    git(&f.mirror, &["update-ref", "refs/heads/main", &next]);
    refused(
        f.prepare(&tree, Some(&f.tip)),
        "expected mirror main tip changed",
    );
}

#[test]
fn generated_mirror_same_source_is_noop_but_different_tree_refuses() {
    let mut f = Fixture::new(true);
    let tree = f.export();
    let v: Value = serde_json::from_str(&output_text(f.prepare(&tree, Some(&f.tip)))).unwrap();
    f.publish_fixture(v["prepared_commit"].as_str().unwrap());
    let value: Value = serde_json::from_str(&output_text(f.prepare(&tree, None))).unwrap();
    assert_eq!(value["no_op"], true);
    assert_eq!(value["prepared_commit"], f.tip);
    let different = f.replace_blob(&tree, "README.md", b"inconsistent generated bytes\n");
    refused(
        f.prepare(&different, None),
        "same source has different export tree or provenance",
    );
}

#[test]
fn subsequent_source_advances_and_older_source_refuses() {
    let mut f = Fixture::new(true);
    let original_source = f.source.clone();
    let first_tree = f.export();
    let v: Value =
        serde_json::from_str(&output_text(f.prepare(&first_tree, Some(&f.tip)))).unwrap();
    f.publish_fixture(v["prepared_commit"].as_str().unwrap());
    f.advance_source();
    let next_tree = f.export();
    let parent = f.tip.clone();
    let next: Value = serde_json::from_str(&output_text(f.prepare(&next_tree, None))).unwrap();
    assert_eq!(
        git(
            &f.root,
            &[
                "show",
                "-s",
                "--format=%P",
                next["prepared_commit"].as_str().unwrap()
            ]
        ),
        parent
    );
    f.publish_fixture(next["prepared_commit"].as_str().unwrap());
    git(
        &f.root,
        &[
            "-c",
            "core.hooksPath=/dev/null",
            "checkout",
            "--quiet",
            "--detach",
            &original_source,
        ],
    );
    f.source = original_source;
    refused(
        f.prepare(&first_tree, None),
        "source must advance the prior source ancestry",
    );
}

#[test]
fn unresolved_or_inconsistent_provenance_refuses() {
    let f = Fixture::new(true);
    let tree = f.export();
    let original: Value = serde_json::from_str(&git(
        &f.root,
        &["show", &format!("{tree}:.jeryu-source.json")],
    ))
    .unwrap();
    for (field, value) in [
        ("lock_regeneration_required", json!(true)),
        ("publication_qualified", json!(true)),
        ("component", json!("jeryu-web")),
        ("original_component_tree", json!("0".repeat(40))),
    ] {
        let mut descriptor = original.clone();
        descriptor[field] = value;
        let bad = f.replace_blob(
            &tree,
            ".jeryu-source.json",
            serde_json::to_string(&descriptor).unwrap().as_bytes(),
        );
        let output = f.prepare(&bad, Some(&f.tip));
        assert_eq!(output.status.code(), Some(1));
        assert!(output.stdout.is_empty());
    }
}

#[test]
fn compiled_generator_drift_refuses_even_with_matching_descriptor() {
    let mut f = Fixture::new(true);
    fs::write(
        f.root
            .join("components/jeryu-deploy/crates/jeryu-split-tool/src/split_ci.sh"),
        "different generator\n",
    )
    .unwrap();
    git(&f.root, &["add", "."]);
    git(
        &f.root,
        &[
            "-c",
            "commit.gpgsign=false",
            "commit",
            "--quiet",
            "-m",
            "Changed generator",
        ],
    );
    f.source = git(&f.root, &["rev-parse", "HEAD"]);
    refused(
        f.prepare(&f.export(), Some(&f.tip)),
        "compiled generator differs from source",
    );
}

#[test]
fn new_or_working_copy_mirrors_and_dirty_sources_are_not_supported() {
    let f = Fixture::new(true);
    let tree = f.export();
    fs::write(f.root.join("uncommitted"), "fixture\n").unwrap();
    refused(
        f.prepare(&tree, Some(&f.tip)),
        "source checkout is not clean",
    );
    let mut f = Fixture::new(true);
    let tree = f.export();
    f.mirror = f.root.clone();
    refused(f.prepare(&tree, Some(&f.tip)), "wrong Git repository kind");
    let f = Fixture::new(true);
    let tree = f.export();
    git(&f.mirror, &["update-ref", "-d", "refs/heads/main"]);
    refused(
        f.prepare(&tree, Some(&f.tip)),
        "offline mirror Git operation failed: rev-parse",
    );
}
