-- Constraints: inline-schema marker
--
-- Durable constraints (PRIMARY KEYs, UNIQUE indexes, NOT NULL) are
-- declared inline with the table definitions in `src/state.rs` and
-- friends because the live schema is created at startup against a
-- local RedlineDB (or in-memory) cache.
--
-- This file exists so the `[db]` boundary in `agent/boundaries.toml`
-- routes to a real constraint artifact. When the schema is extracted
-- into versioned migrations, lift the inline constraints into discrete
-- files under this directory.
--
-- Intentionally a no-op:
SELECT 1 AS inline_constraints_marker;
