[package]
name = "jeryu-api"
version = "0.10.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
jeryu-bench = { path = "../jeryu-bench" }
jeryu-obs = { path = "../jeryu-obs" }
jeryu-enterprise = { path = "../jeryu-enterprise" }

[lints]
workspace = true
