[package]
name = "jit-ci"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
ci-ir = { path = "../../crates/ci-ir" }
ci-compiler = { path = "../../crates/ci-compiler" }
ci-scheduler = { path = "../../crates/ci-scheduler" }
artifact-metadata = { path = "../../crates/artifact-metadata" }
cache-policy = { path = "../../crates/cache-policy" }
runner-protocol = { path = "../../crates/runner-protocol" }

[lints]
workspace = true
