#!/usr/bin/env bash
set -euo pipefail

repo_root_input="${1:-.}"
if ! repo_root="$(cd "$repo_root_input" && pwd)"; then
  echo "unable to resolve repo root: $repo_root_input" >&2
  exit 1
fi
out_dir="$repo_root/target/jankurai/security"
mkdir -p "$out_dir"

json_string() {
  local value="${1//\\/\\\\}"
  value="${value//\"/\\\"}"
  printf '"%s"' "$value"
}

step_status() {
  case "$1" in
    0) printf 'ran' ;;
    *) printf 'failed' ;;
  esac
}

emit_security_step() {
  local label="$1" tool="$2" status_code="$3" advisory="$4" shell_command="$5"
  printf 'jankurai-security-step={"label":%s,"shell_command":%s,"tool":%s,"status":%s,"exit_code":%s,"advisory":%s}\n' \
    "$(json_string "$label")" \
    "$(json_string "$shell_command")" \
    "$(json_string "$tool")" \
    "$(json_string "$(step_status "$status_code")")" \
    "$status_code" \
    "$advisory"
}

gitleaks_report="$out_dir/gitleaks.sarif"
gitleaks_log="$out_dir/gitleaks.log"
cargo_deny_log="$out_dir/cargo-deny.log"
sbom_report="$out_dir/sbom.spdx.json"
syft_log="$out_dir/syft.log"
workflow_lint_log="$out_dir/actionlint.log"

# Generated by prior local runs; unlink first so stale files do not make the
# native Syft run fail with EACCES.
rm -f "$sbom_report"

gitleaks_status=0
cargo_deny_status=0
sbom_status=0
workflow_lint_status=0

require_native_tool() {
  local tool="$1"
  if ! command -v "$tool" >/dev/null 2>&1; then
    echo "security lane requires $tool on PATH; run bash scripts/install-security-tools.sh" >&2
    return 127
  fi
}

if require_native_tool gitleaks; then
  if gitleaks detect \
    --no-banner \
    --no-git \
    --redact \
    --config "$repo_root/.gitleaks.toml" \
    --source "$repo_root" \
    --report-format sarif \
    --report-path "$gitleaks_report" \
    >"$gitleaks_log" 2>&1; then
    gitleaks_status=0
  else
    gitleaks_status=$?
  fi
else
  gitleaks_status=127
fi

if require_native_tool cargo-deny; then
  if cargo deny check >"$cargo_deny_log" 2>&1; then
    cargo_deny_status=0
  else
    cargo_deny_status=$?
  fi
else
  cargo_deny_status=127
fi

if require_native_tool syft; then
  if syft dir:. \
    --exclude './target/**' \
    --exclude './.git/**' \
    --exclude './.jankurai/**' \
    -o spdx-json="$sbom_report" >"$syft_log" 2>&1; then
    sbom_status=0
  else
    sbom_status=$?
  fi
else
  sbom_status=127
fi

if require_native_tool actionlint; then
  if actionlint "$repo_root/.github/workflows"/*.yml >"$workflow_lint_log" 2>&1; then
    workflow_lint_status=0
  else
    workflow_lint_status=$?
  fi
else
  workflow_lint_status=127
fi

status=0
# Fail closed: missing tools are lane failures now that CI installs them
# explicitly before invoking this script.
is_real_failure() { [ "$1" -ne 0 ]; }
if is_real_failure "$gitleaks_status" \
    || is_real_failure "$cargo_deny_status" \
    || is_real_failure "$sbom_status" \
    || is_real_failure "$workflow_lint_status"; then
  status=1
fi

emit_security_step "gitleaks" "gitleaks" "$gitleaks_status" true \
  "gitleaks detect --no-banner --no-git --redact"
emit_security_step "cargo-deny" "cargo-deny" "$cargo_deny_status" true \
  "cargo deny check"
emit_security_step "syft" "syft" "$sbom_status" true \
  "syft dir:. -o spdx-json"
emit_security_step "actionlint" "actionlint" "$workflow_lint_status" true \
  "actionlint .github/workflows/*.yml"

commit="$(git -C "$repo_root" rev-parse HEAD)"
generated_at="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

cat >"$out_dir/evidence.json" <<EOF
{
  "schema_version": "1.0.0",
  "repo_root": $(json_string "$repo_root"),
  "commit": $(json_string "$commit"),
  "generated_at": $(json_string "$generated_at"),
  "secret_scan": {
    "tool": "gitleaks",
    "status": $gitleaks_status,
    "report": "gitleaks.sarif",
    "log": "gitleaks.log"
  },
  "dependency_review": {
    "tool": "cargo deny",
    "status": $cargo_deny_status,
    "report": "cargo-deny.log"
  },
  "sbom": {
    "tool": "syft",
    "status": $sbom_status,
    "report": "sbom.spdx.json",
    "log": "syft.log"
  },
  "workflow_lint": {
    "tool": "actionlint",
    "status": $workflow_lint_status,
    "report": "actionlint.log"
  }
}
EOF

if [ "$status" -ne 0 ]; then
  echo "security lane failed; see $out_dir" >&2
  exit "$status"
fi

echo "security lane evidence written to $out_dir/evidence.json"
