// allowlist: direct-db-access-from-wrong-layer
//! Owner: Git Hook Admission Control
//! Proof: `cargo check -p jeryu` (install is side-effectful; verify with `jeryu server-hook pre-receive`)
//! Invariants: Hook runs before GitLab finalizes push objects; install is idempotent; hook path is resolved through config

use std::io::{self, BufRead};
use std::os::unix::fs::PermissionsExt;
use std::path::PathBuf;
use std::process::Command;

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
/// Pre-receive admission outcome for one ref update.
pub enum AdmissionVerdict {
    /// The push proceeds normally.
    Allow,
    /// The push proceeds while a policy gap is recorded for follow-up.
    Audit,
    /// The push is rejected by admission policy.
    Deny,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
/// Versioned admission proof record for one pre-receive input line.
pub struct AdmissionEvaluation {
    /// Final policy verdict.
    pub verdict: AdmissionVerdict,
    /// Previous object id from Git pre-receive input.
    pub old_sha: Option<String>,
    /// New object id from Git pre-receive input.
    pub new_sha: Option<String>,
    /// Fully qualified ref name.
    pub ref_name: Option<String>,
    /// Coarse actor classification inferred from the ref namespace.
    pub actor_kind: String,
    /// Human and machine readable policy reasons.
    pub reasons: Vec<String>,
    /// Capability grant that satisfied admission, when present.
    pub grant_id: Option<String>,
    /// Whether a fresh backup requirement was satisfied, failed, or not required.
    pub backup_status: Option<String>,
    /// Version of the admission policy contract that produced this record.
    pub policy_version: String,
}

#[path = "admission_logic.rs"]
mod admission_logic;
pub use admission_logic::evaluate_pre_receive_line;

/// Host path for the Gitaly custom hook.
fn hook_path() -> PathBuf {
    crate::config::gitlab_pre_receive_hooks_dir()
}

/// Installs the git server hook globally on the host filesystem
/// so that the GitLab container's Gitaly service will execute it.
pub fn install_global_hook() -> anyhow::Result<()> {
    let hook_dir = hook_path();
    let hook_file = hook_dir.join("jeryu-admission");
    let hook_script = r#"#!/bin/bash
# Autogenerated by jeryu — The Agent OS Admission Controller
# This executes inside the GitLab omnibus container.
export RUST_LOG=info
exec /opt/jeryu/jeryu server-hook pre-receive
"#;

    match install_hook_on_host(&hook_file, hook_script) {
        Ok(()) => {
            tracing::info!(
                "Admission Controller hook installed at {}",
                hook_file.display()
            );
            Ok(())
        }
        Err(err) if is_permission_denied(&err) => {
            tracing::warn!(
                error = %err,
                "host hook install failed; attempting container-side install"
            );
            install_hook_in_gitlab_container(hook_script)?;
            tracing::info!(
                "Admission Controller hook installed in GitLab container at {}",
                hook_file.display()
            );
            Ok(())
        }
        Err(err) => Err(err),
    }
}

fn install_hook_on_host(hook_file: &PathBuf, hook_script: &str) -> anyhow::Result<()> {
    let parent = match hook_file.parent() {
        Some(p) => p,
        None => return Err(anyhow::anyhow!("hook file has no parent")),
    };
    std::fs::create_dir_all(parent)?;
    std::fs::write(hook_file, hook_script)?;

    std::fs::set_permissions(hook_file, std::fs::Permissions::from_mode(0o755))?;
    Ok(())
}

fn install_hook_in_gitlab_container(hook_script: &str) -> anyhow::Result<()> {
    let compose_file = crate::config::compose_file();
    let script = format!(
        r#"mkdir -p /var/opt/gitlab/gitaly/custom_hooks/pre-receive.d && cat > /var/opt/gitlab/gitaly/custom_hooks/pre-receive.d/jeryu-admission <<'EOF'
{hook_script}
EOF
chmod 0755 /var/opt/gitlab/gitaly/custom_hooks/pre-receive.d/jeryu-admission
"#
    );

    let compose_file_str = match compose_file.to_str() {
        Some(s) => s,
        None => return Err(anyhow::anyhow!("compose file path is not valid UTF-8")),
    };
    let status = Command::new("docker")
        .args([
            "compose",
            "-f",
            compose_file_str,
            "exec",
            "-T",
            "gitlab",
            "bash",
            "-lc",
            &script,
        ])
        .status()?;

    if !status.success() {
        return Err(anyhow::anyhow!(
            "container-side hook install failed with status {}",
            status
        ));
    }

    Ok(())
}

fn is_permission_denied(err: &anyhow::Error) -> bool {
    err.chain()
        .any(|cause| cause.to_string().contains("Permission denied"))
}

/// The entrypoint for `jeryu server-hook pre-receive`
/// GitLab invokes this hook when it receives pushes from users or agents,
/// before the objects are finalized in the repository.
///
/// Input format on stdin:
/// `<source-value> <target-value> <ref-name>\n`
pub async fn run_pre_receive_hook() -> anyhow::Result<()> {
    tracing::info!("jeryu admission controller (pre-receive handle) invoked");

    let stdin = io::stdin();
    let mut lines = stdin.lock().lines();
    let enforce = std::env::var("JERYU_ADMISSION_ENFORCE").ok().as_deref() == Some("1");

    while let Some(Ok(line)) = lines.next() {
        tracing::debug!("pre-receive input: {}", line);
        let mut evaluation = evaluate_pre_receive_line(&line, enforce);
        let persisted =
            crate::admission_records::record_decision_for_hook(&line, &evaluation).await;
        if enforce && !persisted && evaluation.actor_kind == "agent" {
            evaluation.verdict = AdmissionVerdict::Deny;
            evaluation
                .reasons
                .push("admission record unavailable".to_string());
        }

        tracing::info!(
            ref_name = evaluation.ref_name.as_deref().unwrap_or("<malformed>"),
            actor_kind = %evaluation.actor_kind,
            verdict = ?evaluation.verdict,
            reasons = ?evaluation.reasons,
            "admission evaluation"
        );

        if evaluation.verdict == AdmissionVerdict::Deny {
            eprintln!(
                "GL-HOOK-ERR: jeryu admission denied: {}",
                evaluation.reasons.join("; ")
            );
            std::process::exit(1);
        }
    }

    Ok(())
}
