//! Owner: Git Hook Admission Control
//! Proof: `cargo check -p jeryu` (install is side-effectful; verify with `jeryu server-hook pre-receive`)
//! Invariants: Hook runs before GitLab finalizes push objects; install is idempotent; hook path is relative to jeryu data dir

use std::io::{self, BufRead};
use std::os::unix::fs::PermissionsExt;
use std::path::PathBuf;
use std::process::Command;

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
/// Pre-receive admission outcome for one ref update.
pub enum AdmissionVerdict {
    /// The update is allowed to continue.
    Allow,
    /// The update is permitted but records a policy gap that must be closed before enforcement.
    Audit,
    /// The update is rejected by admission policy.
    Deny,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
/// Versioned admission proof record for one pre-receive input line.
pub struct AdmissionEvaluation {
    /// Final policy verdict.
    pub verdict: AdmissionVerdict,
    /// Previous object id from Git pre-receive input.
    pub old_sha: Option<String>,
    /// New object id from Git pre-receive input.
    pub new_sha: Option<String>,
    /// Fully qualified ref name.
    pub ref_name: Option<String>,
    /// Coarse actor classification inferred from the ref namespace.
    pub actor_kind: String,
    /// Human and machine readable policy reasons.
    pub reasons: Vec<String>,
    /// Capability grant that satisfied admission, when present.
    pub grant_id: Option<String>,
    /// Version of the admission policy contract that produced this record.
    pub policy_version: String,
}

/// Path relative to the jeryu data directory to place the Gitaly custom hook.
fn hook_path() -> PathBuf {
    crate::config::gitlab_data_dir()
        .join("gitaly")
        .join("custom_hooks")
        .join("pre-receive.d")
}

/// Installs the git server hook globally on the host filesystem
/// so that the GitLab container's Gitaly service will execute it.
pub fn install_global_hook() -> anyhow::Result<()> {
    let hook_dir = hook_path();
    let hook_file = hook_dir.join("jeryu-admission");
    let hook_script = r#"#!/bin/bash
# Autogenerated by jeryu — The Agent OS Admission Controller
# This executes inside the GitLab omnibus container.
export RUST_LOG=info
exec /opt/jeryu/jeryu server-hook pre-receive
"#;

    match install_hook_on_host(&hook_file, hook_script) {
        Ok(()) => {
            tracing::info!(
                "Admission Controller hook installed at {}",
                hook_file.display()
            );
            Ok(())
        }
        Err(err) if is_permission_denied(&err) => {
            tracing::warn!(
                error = %err,
                "host hook install failed; attempting container-side install"
            );
            install_hook_in_gitlab_container(hook_script)?;
            tracing::info!(
                "Admission Controller hook installed in GitLab container at {}",
                hook_file.display()
            );
            Ok(())
        }
        Err(err) => Err(err),
    }
}

fn install_hook_on_host(hook_file: &PathBuf, hook_script: &str) -> anyhow::Result<()> {
    std::fs::create_dir_all(
        hook_file
            .parent()
            .ok_or_else(|| anyhow::anyhow!("hook file has no parent"))?,
    )?;
    std::fs::write(hook_file, hook_script)?;

    let mut perms = std::fs::metadata(hook_file)?.permissions();
    perms.set_mode(0o755);
    std::fs::set_permissions(hook_file, perms)?;
    Ok(())
}

fn install_hook_in_gitlab_container(hook_script: &str) -> anyhow::Result<()> {
    let compose_file = crate::config::compose_file();
    let script = format!(
        r#"mkdir -p /var/opt/gitlab/gitaly/custom_hooks/pre-receive.d && cat > /var/opt/gitlab/gitaly/custom_hooks/pre-receive.d/jeryu-admission <<'EOF'
{hook_script}
EOF
chmod 0755 /var/opt/gitlab/gitaly/custom_hooks/pre-receive.d/jeryu-admission
"#
    );

    let status = Command::new("docker")
        .args([
            "compose",
            "-f",
            compose_file.to_str().unwrap_or_default(),
            "exec",
            "-T",
            "gitlab",
            "bash",
            "-lc",
            &script,
        ])
        .status()?;

    if !status.success() {
        return Err(anyhow::anyhow!(
            "container-side hook install failed with status {}",
            status
        ));
    }

    Ok(())
}

fn is_permission_denied(err: &anyhow::Error) -> bool {
    err.chain()
        .any(|cause| cause.to_string().contains("Permission denied"))
}

/// The entrypoint for `jeryu server-hook pre-receive`
/// GitLab invokes this hook when it receives pushes from users or agents,
/// before the objects are finalized in the repository.
///
/// Input format on stdin:
/// `<old-value> <new-value> <ref-name>\n`
pub async fn run_pre_receive_hook() -> anyhow::Result<()> {
    tracing::info!("jeryu admission controller (pre-receive handle) invoked");

    let stdin = io::stdin();
    let mut lines = stdin.lock().lines();
    let enforce = std::env::var("JERYU_ADMISSION_ENFORCE").ok().as_deref() == Some("1");
    let db = match crate::state::Db::open().await {
        Ok(db) => Some(db),
        Err(e) => {
            tracing::warn!(error = %e, "admission ledger database unavailable");
            None
        }
    };

    while let Some(Ok(line)) = lines.next() {
        tracing::debug!("pre-receive input: {}", line);
        let evaluation = if let Some(db) = &db {
            evaluate_pre_receive_line_with_db(&line, enforce, db).await
        } else {
            let mut evaluation = evaluate_pre_receive_line(&line, enforce);
            if enforce && evaluation.actor_kind == "agent" {
                evaluation.verdict = AdmissionVerdict::Deny;
                evaluation
                    .reasons
                    .push("admission ledger database unavailable".to_string());
            }
            evaluation
        };

        tracing::info!(
            ref_name = evaluation.ref_name.as_deref().unwrap_or("<malformed>"),
            actor_kind = %evaluation.actor_kind,
            verdict = ?evaluation.verdict,
            reasons = ?evaluation.reasons,
            "admission evaluation"
        );

        if let Some(db) = &db {
            let reasons_json =
                serde_json::to_string(&evaluation.reasons).unwrap_or_else(|_| "[]".to_string());
            let payload = serde_json::to_string(&evaluation).unwrap_or_else(|_| "{}".to_string());
            let _ = db
                .record_admission_decision(crate::state::NewAdmissionDecision {
                    raw_input: &line,
                    verdict: evaluation.verdict.label(),
                    actor_kind: &evaluation.actor_kind,
                    ref_name: evaluation.ref_name.as_deref(),
                    old_sha: evaluation.old_sha.as_deref(),
                    new_sha: evaluation.new_sha.as_deref(),
                    grant_id: evaluation.grant_id.as_deref(),
                    policy_version: &evaluation.policy_version,
                    reasons_json: &reasons_json,
                    payload: &payload,
                })
                .await;
        }

        if evaluation.verdict == AdmissionVerdict::Deny {
            eprintln!(
                "GL-HOOK-ERR: jeryu admission denied: {}",
                evaluation.reasons.join("; ")
            );
            std::process::exit(1);
        }
    }

    Ok(())
}

impl AdmissionVerdict {
    /// Stable string label for persisted admission decisions.
    pub fn label(&self) -> &'static str {
        match self {
            Self::Allow => "allow",
            Self::Audit => "audit",
            Self::Deny => "deny",
        }
    }
}

/// Evaluates one standard Git pre-receive line into an admission proof record.
pub fn evaluate_pre_receive_line(line: &str, enforce_agent_ledger: bool) -> AdmissionEvaluation {
    let parts: Vec<&str> = line.split_whitespace().collect();
    if parts.len() != 3 {
        return AdmissionEvaluation {
            verdict: AdmissionVerdict::Deny,
            old_sha: None,
            new_sha: None,
            ref_name: None,
            actor_kind: "unknown".to_string(),
            reasons: vec!["malformed pre-receive input".to_string()],
            grant_id: None,
            policy_version: "admission-v3.01".to_string(),
        };
    }

    let old_sha = parts[0].to_string();
    let new_sha = parts[1].to_string();
    let ref_name = parts[2].to_string();
    let mut reasons = Vec::new();
    let actor_kind = if is_agent_ref(&ref_name) {
        "agent"
    } else {
        "human_or_system"
    }
    .to_string();

    if !looks_like_git_sha(&old_sha) || !looks_like_git_sha(&new_sha) {
        reasons.push("old or new value is not a git object id".to_string());
    }

    if !ref_name.starts_with("refs/") {
        reasons.push("ref name is not fully qualified".to_string());
    }

    if actor_kind == "agent" {
        reasons.push("agent intent ledger verification pending".to_string());
    }

    let invalid_ref = reasons.iter().any(|reason| {
        reason.contains("not a git object id") || reason.contains("not fully qualified")
    });
    let verdict = if invalid_ref || actor_kind == "agent" && enforce_agent_ledger {
        AdmissionVerdict::Deny
    } else if actor_kind == "agent" {
        AdmissionVerdict::Audit
    } else {
        AdmissionVerdict::Allow
    };

    AdmissionEvaluation {
        verdict,
        old_sha: Some(old_sha),
        new_sha: Some(new_sha),
        ref_name: Some(ref_name),
        actor_kind,
        reasons,
        grant_id: None,
        policy_version: "admission-v3.01".to_string(),
    }
}

/// Evaluates one pre-receive line and consults the durable capability ledger.
pub async fn evaluate_pre_receive_line_with_db(
    line: &str,
    enforce_agent_ledger: bool,
    db: &crate::state::Db,
) -> AdmissionEvaluation {
    let mut evaluation = evaluate_pre_receive_line(line, enforce_agent_ledger);
    if evaluation.actor_kind != "agent" {
        return evaluation;
    }

    let Some(ref_name) = evaluation.ref_name.as_deref() else {
        return evaluation;
    };
    let new_sha = evaluation.new_sha.as_deref();
    match db.active_capability_grant_for_ref(ref_name, new_sha).await {
        Ok(Some(grant)) => {
            evaluation.verdict = AdmissionVerdict::Allow;
            evaluation.grant_id = Some(grant.grant_id);
            evaluation
                .reasons
                .retain(|reason| reason != "agent intent ledger verification pending");
            evaluation
                .reasons
                .push("agent write matched active capability grant".to_string());
        }
        Ok(None) => {}
        Err(e) => {
            if enforce_agent_ledger {
                evaluation.verdict = AdmissionVerdict::Deny;
            }
            evaluation
                .reasons
                .push(format!("admission ledger lookup failed: {e}"));
        }
    }
    evaluation
}

fn is_agent_ref(ref_name: &str) -> bool {
    ref_name.starts_with("refs/heads/agent/")
        || ref_name.starts_with("refs/heads/jeryu/")
        || ref_name.starts_with("refs/heads/agents/")
}

fn looks_like_git_sha(value: &str) -> bool {
    value.len() == 40 && value.bytes().all(|b| b.is_ascii_hexdigit())
}

#[cfg(test)]
mod tests {
    use super::*;

    const ZERO: &str = "0000000000000000000000000000000000000000";
    const HEAD: &str = "0123456789abcdef0123456789abcdef01234567";

    #[test]
    fn allows_human_or_system_ref() {
        let eval = evaluate_pre_receive_line(&format!("{ZERO} {HEAD} refs/heads/main"), false);
        assert_eq!(eval.verdict, AdmissionVerdict::Allow);
        assert_eq!(eval.actor_kind, "human_or_system");
    }

    #[test]
    fn audits_agent_ref_until_ledger_enforcement_is_enabled() {
        let eval =
            evaluate_pre_receive_line(&format!("{ZERO} {HEAD} refs/heads/agent/task-123"), false);
        assert_eq!(eval.verdict, AdmissionVerdict::Audit);
        assert_eq!(eval.actor_kind, "agent");
    }

    #[test]
    fn denies_agent_ref_when_enforcement_is_enabled() {
        let eval =
            evaluate_pre_receive_line(&format!("{ZERO} {HEAD} refs/heads/agent/task-123"), true);
        assert_eq!(eval.verdict, AdmissionVerdict::Deny);
    }

    #[test]
    fn denies_malformed_input() {
        let eval = evaluate_pre_receive_line("not enough fields", false);
        assert_eq!(eval.verdict, AdmissionVerdict::Deny);
    }

    #[tokio::test]
    async fn allows_agent_ref_with_active_ledger_grant() -> anyhow::Result<()> {
        let db = crate::state::Db::open_memory().await?;
        let payload = "{}";
        let intent_id = db
            .record_capability_intent(crate::state::NewCapabilityIntent {
                request_id: "req-admission-test",
                intent_type: "ProposePatch",
                action_id: "propose_patch",
                project_id: Some(1),
                ref_name: Some("refs/heads/agent/task-123"),
                target_ref: Some("main"),
                actor: "capability-api",
                status: "executed",
                payload,
            })
            .await?;
        let expires_at = (chrono::Utc::now() + chrono::Duration::hours(1)).to_rfc3339();
        db.approve_capability_grant(crate::state::NewCapabilityGrant {
            intent_id,
            grant_id: "grant-admission-test",
            action_id: "propose_patch",
            project_id: Some(1),
            ref_name: "refs/heads/agent/task-123",
            new_sha: None,
            required_grant: "agent_task",
            status: "approved",
            expires_at: &expires_at,
            payload,
        })
        .await?;

        let eval = evaluate_pre_receive_line_with_db(
            &format!("{ZERO} {HEAD} refs/heads/agent/task-123"),
            true,
            &db,
        )
        .await;
        assert_eq!(eval.verdict, AdmissionVerdict::Allow);
        assert_eq!(eval.grant_id.as_deref(), Some("grant-admission-test"));
        assert!(
            eval.reasons
                .contains(&"agent write matched active capability grant".to_string())
        );
        Ok(())
    }
}
