// allowlist: direct-db-access-from-wrong-layer
//! Owner: Git Hook Admission Control
//! Proof: `cargo check -p jeryu` (install is side-effectful; verify with `jeryu server-hook pre-receive`)
//! Invariants: Hook runs before GitLab finalizes push objects; install is idempotent; hook path is resolved through config

use std::io::{self, BufRead};
use std::os::unix::fs::PermissionsExt;
use std::path::PathBuf;
use std::process::Command;

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
/// Pre-receive admission outcome for one ref update.
pub enum AdmissionVerdict {
    /// The push proceeds normally.
    Allow,
    /// The push proceeds while a policy gap is recorded for follow-up.
    Audit,
    /// The push is rejected by admission policy.
    Deny,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
/// Versioned admission proof record for one pre-receive input line.
pub struct AdmissionEvaluation {
    /// Final policy verdict.
    pub verdict: AdmissionVerdict,
    /// Previous object id from Git pre-receive input.
    pub old_sha: Option<String>,
    /// New object id from Git pre-receive input.
    pub new_sha: Option<String>,
    /// Fully qualified ref name.
    pub ref_name: Option<String>,
    /// Coarse actor classification inferred from the ref namespace.
    pub actor_kind: String,
    /// Human and machine readable policy reasons.
    pub reasons: Vec<String>,
    /// Capability grant that satisfied admission, when present.
    pub grant_id: Option<String>,
    /// Whether a fresh backup requirement was satisfied, failed, or not required.
    pub backup_status: Option<String>,
    /// Version of the admission policy contract that produced this record.
    pub policy_version: String,
}

/// Host path for the Gitaly custom hook.
fn hook_path() -> PathBuf {
    crate::config::gitlab_pre_receive_hooks_dir()
}

/// Installs the git server hook globally on the host filesystem
/// so that the GitLab container's Gitaly service will execute it.
pub fn install_global_hook() -> anyhow::Result<()> {
    let hook_dir = hook_path();
    let hook_file = hook_dir.join("jeryu-admission");
    let hook_script = r#"#!/bin/bash
# Autogenerated by jeryu — The Agent OS Admission Controller
# This executes inside the GitLab omnibus container.
export RUST_LOG=info
exec /opt/jeryu/jeryu server-hook pre-receive
"#;

    match install_hook_on_host(&hook_file, hook_script) {
        Ok(()) => {
            tracing::info!(
                "Admission Controller hook installed at {}",
                hook_file.display()
            );
            Ok(())
        }
        Err(err) if is_permission_denied(&err) => {
            tracing::warn!(
                error = %err,
                "host hook install failed; attempting container-side install"
            );
            install_hook_in_gitlab_container(hook_script)?;
            tracing::info!(
                "Admission Controller hook installed in GitLab container at {}",
                hook_file.display()
            );
            Ok(())
        }
        Err(err) => Err(err),
    }
}

fn install_hook_on_host(hook_file: &PathBuf, hook_script: &str) -> anyhow::Result<()> {
    let parent = match hook_file.parent() {
        Some(p) => p,
        None => return Err(anyhow::anyhow!("hook file has no parent")),
    };
    std::fs::create_dir_all(parent)?;
    std::fs::write(hook_file, hook_script)?;

    std::fs::set_permissions(hook_file, std::fs::Permissions::from_mode(0o755))?;
    Ok(())
}

fn install_hook_in_gitlab_container(hook_script: &str) -> anyhow::Result<()> {
    let compose_file = crate::config::compose_file();
    let script = format!(
        r#"mkdir -p /var/opt/gitlab/gitaly/custom_hooks/pre-receive.d && cat > /var/opt/gitlab/gitaly/custom_hooks/pre-receive.d/jeryu-admission <<'EOF'
{hook_script}
EOF
chmod 0755 /var/opt/gitlab/gitaly/custom_hooks/pre-receive.d/jeryu-admission
"#
    );

    let compose_file_str = match compose_file.to_str() {
        Some(s) => s,
        None => return Err(anyhow::anyhow!("compose file path is not valid UTF-8")),
    };
    let status = Command::new("docker")
        .args([
            "compose",
            "-f",
            compose_file_str,
            "exec",
            "-T",
            "gitlab",
            "bash",
            "-lc",
            &script,
        ])
        .status()?;

    if !status.success() {
        return Err(anyhow::anyhow!(
            "container-side hook install failed with status {}",
            status
        ));
    }

    Ok(())
}

fn is_permission_denied(err: &anyhow::Error) -> bool {
    err.chain()
        .any(|cause| cause.to_string().contains("Permission denied"))
}

/// The entrypoint for `jeryu server-hook pre-receive`
/// GitLab invokes this hook when it receives pushes from users or agents,
/// before the objects are finalized in the repository.
///
/// Input format on stdin:
/// `<source-value> <target-value> <ref-name>\n`
pub async fn run_pre_receive_hook() -> anyhow::Result<()> {
    tracing::info!("jeryu admission controller (pre-receive handle) invoked");

    let stdin = io::stdin();
    let mut lines = stdin.lock().lines();
    let enforce = std::env::var("JERYU_ADMISSION_ENFORCE").ok().as_deref() == Some("1");

    while let Some(Ok(line)) = lines.next() {
        tracing::debug!("pre-receive input: {}", line);
        let mut evaluation = evaluate_pre_receive_line(&line, enforce);
        let persisted =
            crate::admission_records::record_decision_for_hook(&line, &evaluation).await;
        if enforce && !persisted && evaluation.actor_kind == "agent" {
            evaluation.verdict = AdmissionVerdict::Deny;
            evaluation
                .reasons
                .push("admission record unavailable".to_string());
        }

        tracing::info!(
            ref_name = evaluation.ref_name.as_deref().unwrap_or("<malformed>"),
            actor_kind = %evaluation.actor_kind,
            verdict = ?evaluation.verdict,
            reasons = ?evaluation.reasons,
            "admission evaluation"
        );

        if evaluation.verdict == AdmissionVerdict::Deny {
            eprintln!(
                "GL-HOOK-ERR: jeryu admission denied: {}",
                evaluation.reasons.join("; ")
            );
            std::process::exit(1);
        }
    }

    Ok(())
}

impl AdmissionVerdict {
    /// Stable string label for persisted admission decisions.
    pub fn label(&self) -> &'static str {
        match self {
            Self::Allow => "allow",
            Self::Audit => "audit",
            Self::Deny => "deny",
        }
    }
}

/// Evaluates one standard Git pre-receive line into an admission proof record.
pub fn evaluate_pre_receive_line(line: &str, enforce_agent_grant: bool) -> AdmissionEvaluation {
    evaluate_pre_receive_line_with_context(
        line,
        enforce_agent_grant,
        std::env::var("JERYU_ADMISSION_ACTOR").ok().as_deref(),
        is_non_fast_forward_marker(),
    )
}

#[cfg(test)]
fn evaluate_pre_receive_line_with_actor(
    line: &str,
    enforce_agent_grant: bool,
    actor_override: Option<&str>,
) -> AdmissionEvaluation {
    evaluate_pre_receive_line_with_context(line, enforce_agent_grant, actor_override, false)
}

fn evaluate_pre_receive_line_with_context(
    line: &str,
    enforce_agent_grant: bool,
    actor_override: Option<&str>,
    non_fast_forward: bool,
) -> AdmissionEvaluation {
    let parts: Vec<&str> = line.split_whitespace().collect();
    if parts.len() != 3 {
        return AdmissionEvaluation {
            verdict: AdmissionVerdict::Deny,
            old_sha: None,
            new_sha: None,
            ref_name: None,
            actor_kind: "unknown".to_string(),
            reasons: vec!["malformed pre-receive input".to_string()],
            grant_id: None,
            backup_status: None,
            policy_version: "admission-v3.01".to_string(),
        };
    }

    let old_sha = parts[0].to_string();
    let new_sha = parts[1].to_string();
    let ref_name = parts[2].to_string();
    let mut reasons = Vec::new();
    let actor_kind = if actor_override == Some("jeryu") {
        "jeryu"
    } else if is_agent_ref(&ref_name) {
        "agent"
    } else {
        "human_or_system"
    }
    .to_string();

    if !looks_like_git_sha(&old_sha) || !looks_like_git_sha(&new_sha) {
        reasons.push("source or target value is not a git object id".to_string());
    }

    if !ref_name.starts_with("refs/") {
        reasons.push("ref name is not fully qualified".to_string());
    }

    if actor_kind == "agent" {
        reasons.push("agent intent grant verification pending".to_string());
    }
    apply_protected_ref_policy(
        &old_sha,
        &new_sha,
        &ref_name,
        &actor_kind,
        non_fast_forward,
        &mut reasons,
    );

    let invalid_ref = reasons.iter().any(|reason| {
        reason.contains("not a git object id") || reason.contains("not fully qualified")
    });
    let protected_denial = reasons.iter().any(|reason| {
        reason.starts_with("protected branch")
            || reason.starts_with("protected tag")
            || reason.starts_with("non-fast-forward")
    });
    let verdict = if invalid_ref || protected_denial || actor_kind == "agent" && enforce_agent_grant
    {
        AdmissionVerdict::Deny
    } else if actor_kind == "agent" {
        AdmissionVerdict::Audit
    } else {
        AdmissionVerdict::Allow
    };

    AdmissionEvaluation {
        verdict,
        old_sha: Some(old_sha),
        new_sha: Some(new_sha),
        ref_name: Some(ref_name),
        actor_kind,
        reasons,
        grant_id: None,
        backup_status: Some("not_required".to_string()),
        policy_version: "admission-v3.01".to_string(),
    }
}

fn apply_protected_ref_policy(
    old_sha: &str,
    new_sha: &str,
    ref_name: &str,
    actor_kind: &str,
    non_fast_forward: bool,
    reasons: &mut Vec<String>,
) {
    if is_protected_branch(ref_name) {
        if is_delete(new_sha) {
            reasons.push("protected branch removal denied".to_string());
        } else if actor_kind != "jeryu" && !is_create(old_sha) {
            reasons.push("protected branch direct push denied; use JeRyu main-relay".to_string());
        }
        if non_fast_forward {
            reasons.push("non-fast-forward protected branch push denied".to_string());
        }
    }

    if is_protected_tag(ref_name) && !is_create(old_sha) {
        if is_delete(new_sha) {
            reasons.push("protected tag removal denied".to_string());
        } else {
            reasons.push("protected tag rewrite denied".to_string());
        }
    }
}

fn is_protected_branch(ref_name: &str) -> bool {
    matches!(ref_name, "refs/heads/main" | "refs/heads/master")
}

fn is_protected_tag(ref_name: &str) -> bool {
    ref_name.starts_with("refs/tags/v")
}

fn is_create(old_sha: &str) -> bool {
    old_sha.bytes().all(|b| b == b'0')
}

fn is_delete(new_sha: &str) -> bool {
    new_sha.bytes().all(|b| b == b'0')
}

fn is_non_fast_forward_marker() -> bool {
    std::env::var("JERYU_ADMISSION_NON_FAST_FORWARD")
        .ok()
        .as_deref()
        == Some("1")
}

fn is_agent_ref(ref_name: &str) -> bool {
    ref_name.starts_with("refs/heads/agent/")
        || ref_name.starts_with("refs/heads/jeryu/")
        || ref_name.starts_with("refs/heads/agents/")
}

fn looks_like_git_sha(value: &str) -> bool {
    value.len() == 40 && value.bytes().all(|b| b.is_ascii_hexdigit())
}

#[cfg(test)]
#[path = "admission_tests.rs"]
mod admission_tests;
