use anyhow::{Context, Result};
use std::fs;
use tracing::info;

use crate::config;
use crate::db::config as db_config;

pub(crate) fn generate_password(len: usize) -> String {
    use rand::Rng;
    let mut rng = rand::rng();
    (0..len)
        .map(|_| {
            let idx = rng.random_range(0..62);
            match idx {
                0..=9 => (b'0' + idx) as char,
                10..=35 => (b'a' + idx - 10) as char,
                _ => (b'A' + idx - 36) as char,
            }
        })
        .collect()
}

/// Generate the initial jeryu.env with root password and webhook secret.
/// Does NOT overwrite if it already exists (preserves existing secrets).
pub(crate) fn generate_env_file() -> Result<(String, String)> {
    let env_path = config::env_file();

    if env_path.exists() {
        // Load existing
        info!("jeryu.env already exists, loading existing secrets");
        dotenvy::from_path(&env_path).ok();
        let root_pw = std::env::var("GITLAB_ROOT_PASSWORD")
            .context("GITLAB_ROOT_PASSWORD not found in existing jeryu.env")?;
        let webhook_secret = match std::env::var("JERYU_WEBHOOK_SECRET") {
            Ok(v) => v,
            Err(_) => generate_password(32),
        };
        return Ok((root_pw, webhook_secret));
    }

    let root_password = generate_password(24);
    let webhook_secret = generate_password(32);

    if let Some(parent) = env_path.parent() {
        fs::create_dir_all(parent)?;
    }

    let database_url = db_config::embedded_redline_url(&db_config::state_path());
    let content = format!(
        "# Generated by jeryu bootstrap — do not share\n\
         GITLAB_ROOT_PASSWORD={root_password}\n\
         JERYU_WEBHOOK_SECRET={webhook_secret}\n\
         JERYU_DATABASE_URL={database_url}\n\
         # PAT and runner tokens will be appended after bootstrap\n",
    );

    fs::write(&env_path, &content).with_context(|| format!("writing {}", env_path.display()))?;

    info!(path = %env_path.display(), "generated jeryu.env");
    Ok((root_password, webhook_secret))
}

/// Append a key=value to jeryu.env
pub(crate) fn append_env(key: &str, value: &str) -> Result<()> {
    let env_path = config::env_file();
    let line = format!("{}={}\n", key, value);
    fs::OpenOptions::new()
        .append(true)
        .open(&env_path)
        .with_context(|| format!("opening {} for append", env_path.display()))?;
    fs::write(
        &env_path,
        format!("{}{}", fs::read_to_string(&env_path)?, line),
    )?;
    Ok(())
}
