//! Owner: Bootstrap subsystem
//! Proof: `cargo nextest run -p jeryu -- bootstrap`
//! Invariants: Bootstrap remains non-interactive and records generated credentials only in local env files.
//! Headless bootstrap: from zero to running GitLab + Rust god-mode.
//!
//! `jeryu bootstrap` executes this entire sequence with no human
//! interaction required:
//!
//! 1. Generate secrets → jeryu.env
//! 2. Write docker-compose.yml
//! 3. Start GitLab container
//! 4. Wait for readiness
//! 5. Create root PAT via OAuth
//! 6. Create runner pools via API
//! 7. Register group webhook
//! 8. Start warm runner managers
//! 9. Print summary

use anyhow::{Context, Result, bail};
use std::fs;
use tracing::info;

use crate::config;
use crate::db::config as db_config;
use crate::docker::DockerCtl;
use crate::gitlab_client::GitlabClient;
use crate::secrets;
use crate::state::{Db, Pool};

// ---------------------------------------------------------------------------
// Secrets generation
// ---------------------------------------------------------------------------

fn generate_password(len: usize) -> String {
    use rand::Rng;
    let mut rng = rand::rng();
    (0..len)
        .map(|_| {
            let idx = rng.random_range(0..62);
            match idx {
                0..=9 => (b'0' + idx) as char,
                10..=35 => (b'a' + idx - 10) as char,
                _ => (b'A' + idx - 36) as char,
            }
        })
        .collect()
}

/// Generate the initial jeryu.env with root password and webhook secret.
/// Does NOT overwrite if it already exists (preserves existing secrets).
fn generate_env_file() -> Result<(String, String)> {
    let env_path = config::env_file();

    if env_path.exists() {
        // Load existing
        info!("jeryu.env already exists, loading existing secrets");
        dotenvy::from_path(&env_path).ok();
        let root_pw = std::env::var("GITLAB_ROOT_PASSWORD")
            .context("GITLAB_ROOT_PASSWORD not found in existing jeryu.env")?;
        let webhook_secret = match std::env::var("JERYU_WEBHOOK_SECRET") {
            Ok(v) => v,
            Err(_) => generate_password(32),
        };
        return Ok((root_pw, webhook_secret));
    }

    let root_password = generate_password(24);
    let webhook_secret = generate_password(32);

    if let Some(parent) = env_path.parent() {
        fs::create_dir_all(parent)?;
    }

    let database_url = db_config::embedded_redline_url(&db_config::state_path());
    let content = format!(
        "# Generated by jeryu bootstrap — do not share\n\
         GITLAB_ROOT_PASSWORD={root_password}\n\
         JERYU_WEBHOOK_SECRET={webhook_secret}\n\
         JERYU_DATABASE_URL={database_url}\n\
         # PAT and runner tokens will be appended after bootstrap\n",
    );

    fs::write(&env_path, &content).with_context(|| format!("writing {}", env_path.display()))?;

    info!(path = %env_path.display(), "generated jeryu.env");
    Ok((root_password, webhook_secret))
}

/// Append a key=value to jeryu.env
fn append_env(key: &str, value: &str) -> Result<()> {
    let env_path = config::env_file();
    let line = format!("{}={}\n", key, value);
    fs::OpenOptions::new()
        .append(true)
        .open(&env_path)
        .with_context(|| format!("opening {} for append", env_path.display()))?;
    fs::write(
        &env_path,
        format!("{}{}", fs::read_to_string(&env_path)?, line),
    )?;
    Ok(())
}

// ---------------------------------------------------------------------------
// Bootstrap
// ---------------------------------------------------------------------------

pub async fn run_bootstrap() -> Result<()> {
    println!("🚀 jeryu bootstrap — headless GitLab setup\n");

    // Step 1: Generate secrets
    println!("  [1/8] Generating secrets...");
    let (root_password, _webhook_secret) = generate_env_file()?;

    // Step 2: Write docker-compose.yml
    println!("  [2/8] Writing docker-compose.yml...");
    let compose_content = config::render_compose(&root_password);
    let compose_path = config::compose_file();
    if let Some(parent) = compose_path.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(&compose_path, &compose_content)?;

    // Ensure GitLab volume directories exist
    fs::create_dir_all(config::gitlab_config_dir())?;
    fs::create_dir_all(config::gitlab_logs_dir())?;
    fs::create_dir_all(config::gitlab_data_dir())?;
    fs::create_dir_all(config::runners_dir())?;
    fs::create_dir_all(config::vault_config_dir())?;
    fs::create_dir_all(config::vault_storage_dir())?;

    // Step 3: Start GitLab
    println!("  [3/8] Starting GitLab container (this may take a minute)...");
    let docker = DockerCtl::connect()?;
    docker.compose_up().await?;

    println!("  [3b/8] Initializing local Vault...");
    let vault_status = secrets::run_secrets_init(None).await?;
    println!(
        "    ✅ Vault ready at {} (mount={}, prefix={})",
        vault_status.addr, vault_status.mount, vault_status.prefix
    );

    // Step 4: Wait for readiness
    println!("  [4/8] Waiting for GitLab to become ready...");
    let gitlab_url = format!("http://localhost:{}", config::GITLAB_HTTP_PORT);
    let client = GitlabClient::new(&gitlab_url, None);

    let max_wait = std::time::Duration::from_secs(300); // 5 minutes
    let poll_interval = std::time::Duration::from_secs(5);
    let start = std::time::Instant::now();

    loop {
        if client.is_ready().await {
            println!("    ✅ GitLab is ready!");
            break;
        }
        if start.elapsed() > max_wait {
            bail!(
                "GitLab did not become ready within {} seconds. \
                 Check `docker logs jeryu-gitlab` for details.",
                max_wait.as_secs()
            );
        }
        print!(
            "    ⏳ waiting ({:.0}s)...\r",
            start.elapsed().as_secs_f64()
        );
        tokio::time::sleep(poll_interval).await;
    }

    // Step 5: Create root PAT programmatically (bypassing OAuth ROPC)
    println!("  [5/8] Creating root PAT via gitlab-rails...");
    let pat = format!("jeryu-pat-{}", generate_password(20));

    let rails_script = format!(
        "u = User.find_by_username('root');\
         t = u.personal_access_tokens.create!(scopes: ['api', 'create_runner', 'manage_runner', 'read_repository', 'write_repository'], name: 'jeryu-control-plane', expires_at: 365.days.from_now);\
         t.set_token('{}');\
         t.save!",
        pat
    );

    let output = tokio::process::Command::new("docker")
        .args([
            "exec",
            "jeryu-gitlab",
            "gitlab-rails",
            "runner",
            &rails_script,
        ])
        .output()
        .await
        .context("running gitlab-rails runner to create PAT")?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        anyhow::bail!("failed to create PAT via gitlab-rails: {}", stderr);
    }

    append_env("GITLAB_PAT", &pat)?;
    println!("    ✅ PAT stored in jeryu.env");

    // Now create an authenticated client
    let client = GitlabClient::new(&gitlab_url, Some(pat.clone()));

    // Step 6: Create runner pools
    println!("  [6/8] Creating runner pools...");
    let db = Db::open().await?;

    for pool_def in config::DEFAULT_POOLS {
        let tags: Vec<&str> = pool_def.tags.split(',').collect();
        let runner = client
            .create_runner(
                &format!("jeryu-{}", pool_def.name),
                &tags,
                pool_def.name == "default", // only default runs untagged
                "instance_type",
            )
            .await
            .with_context(|| format!("creating runner pool: {}", pool_def.name))?;

        // Store token in env file
        let env_key = format!("RUNNER_TOKEN_{}", pool_def.name.to_uppercase());
        append_env(&env_key, &runner.token)?;

        // Store in database
        let pool = Pool {
            name: pool_def.name.to_string(),
            gitlab_runner_id: runner.id,
            auth_token: runner.token.clone(),
            tags: pool_def.tags.to_string(),
            executor: pool_def.executor.to_string(),
            min_warm: pool_def.min_warm,
            max_managers: pool_def.max_managers,
            concurrent: pool_def.concurrent,
            request_concurrency: pool_def.request_concurrency,
            paused: false,
            trust_tier: pool_def.trust_tier.to_string(),
        };
        db.insert_pool(&pool).await?;

        println!(
            "    ✅ Pool '{}' created (runner_id={})",
            pool_def.name, runner.id
        );
    }

    // Step 7: Register webhook
    // Note: On fresh installs, the root user's namespace is group_id=1 typically,
    // but we'll use project-level webhooks or skip if no group exists yet.
    // For now, we'll document this as a post-bootstrap step since you need
    // at least one project/group to attach a webhook to.
    println!("  [7/8] Webhook registration...");
    println!("    ℹ️  Webhook will be registered when the first project/group is created.");
    println!("    ℹ️  Webhook secret stored in jeryu.env for later use.");

    // Step 8: Install always-on disk daemon (jeryu-gcd.service).
    // Maintains df >= 80 GiB free; the rest of bootstrap depends on this.
    // Skipped when JERYU_BOOTSTRAP_SKIP_GCD=1 (CI/containers) or when
    // systemctl is unavailable.
    if std::env::var("JERYU_BOOTSTRAP_SKIP_GCD").as_deref() == Ok("1") {
        println!("  [8/9] jeryu-gcd install... ⊘ skipped (JERYU_BOOTSTRAP_SKIP_GCD=1)");
    } else {
        println!("  [8/9] Installing jeryu-gcd.service (always-on disk daemon)...");
        match crate::host::install_gcd_service(true).await {
            Ok(_) => println!("    ✅ jeryu-gcd.service installed and enabled."),
            Err(err) => {
                eprintln!(
                    "    ⚠️  jeryu-gcd install failed (continuing bootstrap): {err}\n       Run `jeryu host install-gcd-service --allow-sudo` manually."
                );
            }
        }
    }

    // Step 9: Validation (The Smoke Test)
    println!("  [9/9] Running smoke test (validating end-to-end CI)...");
    let test_project = client.create_project("jeryu-smoke-test").await?;

    let ci_yaml = r#"
smoke_test:
  tags: [rust]
  script:
    - echo "━━━ jeryu smoke test ━━━"
    - echo "God Mode: Enabled"
    - hostname
    - uname -a
"#;
    client
        .create_file(
            test_project.id,
            "main",
            ".gitlab-ci.yml",
            ci_yaml,
            "Init smoke test",
        )
        .await?;
    println!("    ✅ Smoke test project created and pipeline triggered.");
    println!("    ℹ️  Run `jeryu up` to start the engine and process this job.");

    // Summary
    println!("\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");
    println!("  ✅ jeryu bootstrap complete!");
    println!("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");
    println!();
    println!("  GitLab URL:     {}", gitlab_url);
    println!(
        "  SSH:            ssh://git@localhost:{}",
        config::GITLAB_SSH_PORT
    );
    println!("  Root user:      root");
    println!("  Secrets file:   {}", config::env_file().display());
    println!("  Database:       {}", db_config::state_path().display());
    println!("  Runner configs: {}", config::runners_dir().display());
    println!();
    println!("  Pools:");
    let pools = match db.list_pools().await {
        Ok(p) => p,
        Err(_) => Vec::new(),
    };
    for p in &pools {
        let active = db.count_active_managers(&p.name).await.unwrap_or(0);
        println!(
            "    {:<15} runners={:<3} managers={}/{}",
            p.name, p.gitlab_runner_id, active, p.max_managers
        );
    }
    println!();
    println!("  Next steps:");
    println!("    jeryu status          — check system health");
    println!("    jeryu pool list       — show pools and managers");
    println!("    jeryu agent spawn ... — launch an autonomous agent");
    println!();

    Ok(())
}
