//! Owner: Failure Capsule subsystem
//! Proof: `cargo nextest run -p jeryu -- capsule`
//! Invariants: Capsules stay structured, redacted, and sufficient to reproduce a failed job.
//! Failure Capsule: Structured error reporting for AI diagnostics.
//!
//! A capsule bundles the exit status, log snippets, and environment
//! context of a failed job into a single JSON object.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::env;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FailureCapsule {
    pub job_id: i64,
    pub pipeline_id: Option<i64>,
    pub project_id: i64,
    pub stage: String,
    pub exit_code: i32,
    pub commit_sha: String,
    pub ref_name: String,
    pub working_directory: String,
    pub log_snippet: String,
    pub repro_script: String,
    pub environment: HashMap<String, String>,
    pub failure_kind: String,
    pub summary: String,
    pub superseded_by_sha: Option<String>,
    pub requeued_from_job_id: Option<i64>,
}

impl FailureCapsule {
    /// Capture the current execution environment into a FailureCapsule.
    /// This is typically called from the custom executor (jeryu exec) when a stage fails.
    pub fn capture(
        job_id: i64,
        project_id: i64,
        stage: &str,
        exit_code: i32,
        log_snippet: String,
        repro_script: &str,
    ) -> Self {
        let mut environment = HashMap::new();
        let pipeline_id = env::var("CUSTOM_ENV_CI_PIPELINE_ID")
            .ok()
            .and_then(|value| value.parse::<i64>().ok());

        let commit_sha = env_string_or_default(env::var("CUSTOM_ENV_CI_COMMIT_SHA"), "HEAD");
        let ref_name = env_string_or_default(env::var("CUSTOM_ENV_CI_COMMIT_REF_NAME"), "main"); // allowlist: default path intentional
        let working_directory =
            env_string_or_default(env::var("CUSTOM_ENV_CI_PROJECT_DIR"), "/builds");

        // Capture relevant CUSTOM_ENV_* variables provided by GitLab Runner
        for (key, value) in env::vars() {
            if key.starts_with("CUSTOM_ENV_CI_") || key.starts_with("GITLAB_") {
                environment.insert(key, value);
            }
        }

        let mut repro_script_content = String::new();
        repro_script_content.push_str("#!/bin/bash\n");
        repro_script_content
            .push_str("# Deterministic Replay Capsule - Auto-generated by jeryu Agent OS\n\n");
        repro_script_content.push_str("set -e\n");
        repro_script_content.push_str(&format!("cd {}\n", working_directory));
        repro_script_content.push_str(&format!("git fetch origin {}\n", ref_name));
        repro_script_content.push_str(&format!("git checkout {}\n\n", commit_sha));

        repro_script_content.push_str("# --- Environment ---\n");
        // Filter sensitive tokens explicitly for offline scripts
        for (k, v) in &environment {
            if !k.contains("TOKEN")
                && !k.contains("KEY")
                && !k.contains("SECRET")
                && !k.contains("PASSWORD")
            {
                repro_script_content.push_str(&format!(
                    "export {}=\"{}\"\n",
                    k,
                    v.replace('\"', "\\\"")
                ));
            }
        }

        repro_script_content.push_str("\n# --- Original Command ---\n");
        repro_script_content.push_str(repro_script);
        repro_script_content.push('\n');

        let log_lower = log_snippet.to_ascii_lowercase();
        let failure_kind = classify_failure_kind(stage, exit_code, &log_lower);
        let summary = format!(
            "{} failure in stage '{}' on ref '{}'",
            failure_kind, stage, ref_name
        );

        Self {
            job_id,
            pipeline_id,
            project_id,
            stage: stage.to_string(),
            exit_code,
            commit_sha,
            ref_name,
            working_directory,
            log_snippet,
            repro_script: repro_script_content,
            environment,
            failure_kind,
            summary,
            superseded_by_sha: None,
            requeued_from_job_id: None,
        }
    }

    pub fn classify(&self) -> crate::decision::FailureClassification {
        crate::decision::classify_failure(self)
    }

    pub fn recommended_recovery(&self) -> crate::decision::RetryDecision {
        crate::decision::recommend_recovery(self)
    }

    /// Serialize to JSON for storage in the event ledger.
    pub fn to_json(&self) -> String {
        match serde_json::to_string(self) {
            Ok(s) => s,
            Err(_) => "{}".to_string(),
        }
    }
}

fn env_string_or_default(value: Result<String, env::VarError>, default: &'static str) -> String {
    match value {
        Ok(value) => value,
        Err(_) => default.to_string(),
    }
}

fn classify_failure_kind(stage: &str, exit_code: i32, log_lower: &str) -> String {
    if crate::ci_failure::is_source_fetch_auth_failure(log_lower) {
        return crate::ci_failure::SOURCE_FETCH_AUTH_FAILURE_KIND.to_string();
    }
    if exit_code == 999 || log_lower.contains("quarantined") {
        return "quarantined".to_string();
    }
    if exit_code == 124 || log_lower.contains("timed out") || log_lower.contains("timeout") {
        return "timeout".to_string();
    }
    if stage.contains("prepare")
        || log_lower.contains("preparing environment")
        || log_lower.contains("runner system failure")
    {
        return "runner_prep".to_string();
    }
    if log_lower.contains("connection reset")
        || log_lower.contains("network")
        || log_lower.contains("transient failure")
        || log_lower.contains("could not resolve host")
    {
        return "network".to_string();
    }
    if log_lower.contains("could not compile")
        || log_lower.contains("error[E")
        || log_lower.contains("clippy")
    {
        return "compile_failure".to_string();
    }
    if log_lower.contains("test failed") || log_lower.contains("assertion") {
        return "test_failure".to_string();
    }
    "unknown".to_string()
}

#[cfg(test)]
mod tests {
    use super::env_string_or_default;

    #[test]
    fn env_string_or_default_returns_present_value() {
        let value = env_string_or_default(Ok("value".to_string()), "default");

        assert_eq!(value, "value");
    }

    #[test]
    fn env_string_or_default_returns_default_when_missing() {
        let value = env_string_or_default(Err(std::env::VarError::NotPresent), "default");

        assert_eq!(value, "default");
    }
}
