//! Owner: Configuration & Templates subsystem
//! Proof: `cargo nextest run -p jeryu -- config`
//! Invariants: Defaults and templates remain deterministic, local, and safe for unattended bootstrap.
//! Embedded templates and configuration constants for jeryu.
//!
//! This module owns the docker-compose.yml template, runner config.toml
//! template, and all default values that flow through the system.

use std::path::PathBuf;

#[path = "config_compose.rs"]
mod compose;
#[path = "config_paths.rs"]
mod paths;
#[path = "config_support.rs"]
mod support;

pub use compose::render_compose;
pub use paths::*;
pub use support::*;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ConfigLoadMode {
    Permissive,
    FailClosed,
}

// ---------------------------------------------------------------------------
// Runner config.toml Template
// ---------------------------------------------------------------------------

#[allow(clippy::too_many_arguments)] // runner config builder: each arg maps to a specific gitlab-runner TOML field
pub fn render_runner_config(
    pool_name: &str,
    manager_id: &str,
    gitlab_url: &str,
    token: &str,
    executor: &str,
    cache_dir: &str,
    concurrent: i64,
    request_concurrency: i64,
) -> String {
    let pool_cache_mount = pool_cache_mount_path(executor);
    let builds_dir = manager_builds_dir(pool_name, manager_id);
    let cargo_pre_build_script =
        crate::cargo_cache::render_runner_cargo_pre_build_script(pool_cache_mount, executor);
    let executor_block = match executor {
        "custom" => format!(
            r#"  executor = "custom"
  shell = "sh"
  pre_get_sources_script = "export SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt CARGO_HTTP_CAINFO=/etc/ssl/certs/ca-certificates.crt GIT_SSL_CAINFO=/etc/ssl/certs/ca-certificates.crt NODE_EXTRA_CA_CERTS=/etc/ssl/certs/ca-certificates.crt; mkdir -p {pool_cache_mount}"
  [runners.custom_build_dir]
    enabled = true

  [runners.custom]
    # In Phase 2, we use our own Rust binary to handle container lifecycles.
    # The 'jeryu' binary is mounted into the manager container from the host.
    config_exec = "/usr/local/bin/jeryu"
    config_args = ["exec", "config"]

    prepare_exec = "/usr/local/bin/jeryu"
    prepare_args = ["exec", "prepare"]

    run_exec = "/usr/local/bin/jeryu"
    run_args = ["exec", "run"]

    cleanup_exec = "/usr/local/bin/jeryu"
    cleanup_args = ["exec", "cleanup"]"#,
            pool_cache_mount = pool_cache_mount,
        ),
        _ => {
            let ca_cert = "/etc/ssl/certs/ca-certificates.crt";
            let privileged = if pool_name == "build" {
                "true"
            } else {
                "false"
            };
            format!(
                r#"  executor = "docker"
  pre_get_sources_script = "export SSL_CERT_FILE={ca_cert} CARGO_HTTP_CAINFO={ca_cert} GIT_SSL_CAINFO={ca_cert} NODE_EXTRA_CA_CERTS={ca_cert}; mkdir -p /cache; if [ -n \"$CI_PROJECT_DIR\" ] && [ -d \"$CI_PROJECT_DIR\" ]; then if [ -d \"$CI_PROJECT_DIR/.git\" ]; then rm -f \"$CI_PROJECT_DIR/.git/shallow.lock\" \"$CI_PROJECT_DIR/.git/index.lock\"; git -C \"$CI_PROJECT_DIR\" remote get-url origin >/dev/null 2>&1 || rm -rf \"$CI_PROJECT_DIR\"; else rm -rf \"$CI_PROJECT_DIR\"; fi; fi"
  pre_build_script = {cargo_pre_build_script:?}
  [runners.custom_build_dir]
    enabled = true

  [runners.docker]
    image = "rust:1.92.0"
    pull_policy = "if-not-present"
    allowed_pull_policies = ["always", "if-not-present", "never"]
    privileged = {privileged}
    volumes = ["{ca_cert}:{ca_cert}:ro", "{cache_dir}:/cache:rw"]
    extra_hosts = ["host.docker.internal:host-gateway", "gitlab.local:host-gateway"]"#
            )
        }
    };

    format!(
        r#"# Generated by jeryu — pool: {pool_name}
concurrent = {concurrent}
check_interval = 3
log_format = "json"
listen_address = "0.0.0.0:9252"
shutdown_timeout = 3600

[[runners]]
  name = "jeryu-{pool_name}"
  url = "{gitlab_url}"
  token = "{token}"
  builds_dir = "{builds_dir}"
  limit = {concurrent}
  request_concurrency = {request_concurrency}
  environment = [
    "SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt",
    "CARGO_HTTP_CAINFO=/etc/ssl/certs/ca-certificates.crt",
    "GIT_SSL_CAINFO=/etc/ssl/certs/ca-certificates.crt",
    "NODE_EXTRA_CA_CERTS=/etc/ssl/certs/ca-certificates.crt",
    "JERYU_SCCACHE_ENABLED={sccache_enabled}",
    "JERYU_SCCACHE_CACHE_SIZE={sccache_cache_size}",
    "JERYU_SCCACHE_BINARY_VERSION={sccache_binary_version}",
    "JERYU_CARGO_INCREMENTAL=0",
    "JERYU_CARGO_CACHE=1",
    "JERYU_CARGO_CACHE_ROOT={pool_cache_mount}",
    "JERYU_CARGO_TARGET_ISOLATE=slot",
  ]
{executor_block}
"#,
        pool_name = pool_name,
        concurrent = concurrent,
        gitlab_url = gitlab_url,
        token = token,
        builds_dir = builds_dir,
        request_concurrency = request_concurrency,
        executor_block = executor_block,
        sccache_enabled = if crate::settings::get().sccache.enabled {
            "1"
        } else {
            "0"
        },
        sccache_cache_size = crate::settings::get().sccache.cache_size,
        sccache_binary_version = crate::settings::get().sccache.binary_version,
        pool_cache_mount = pool_cache_mount,
    )
}
