use std::path::PathBuf;

pub fn render_compose(root_password: &str) -> String {
    let cfg = super::gitlab_config_dir().display().to_string();
    let logs = super::gitlab_logs_dir().display().to_string();
    let data = super::gitlab_data_dir().display().to_string();
    let vault_data = super::vault_storage_dir().display().to_string();
    let vault_local_config = super::yaml_block(&super::render_vault_local_config(), 8);
    let jeryu_bin_path = match std::env::current_exe() {
        Ok(path) => path,
        Err(_) => PathBuf::from("jeryu"),
    };

    format!(
        r#"# docker-compose.yml - Generated by jeryu bootstrap — do not edit manually
services:
  vault:
    image: {vault_image}
    container_name: {vault_container}
    restart: unless-stopped
    command: server
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_ADDR: "http://127.0.0.1:{vault_port}"
      VAULT_API_ADDR: "http://127.0.0.1:{vault_port}"
      VAULT_LOG_LEVEL: "warn"
      VAULT_LOCAL_CONFIG: |
{vault_local_config}
    ports:
      - "127.0.0.1:{vault_port}:8200"
    volumes:
      - "{vault_data}:/vault/file"
    healthcheck:
      test: ["CMD", "vault", "status"]
      interval: 10s
      timeout: 5s
      retries: 20

  gitlab:
    image: {image}
    container_name: jeryu-gitlab
    hostname: {hostname}
    restart: unless-stopped
    environment:
      GITLAB_ROOT_PASSWORD: "{root_password}"
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://{hostname}:{http_port}'
        gitlab_rails['gitlab_shell_ssh_port'] = {ssh_port}
        gitlab_workhorse['api_ci_long_polling_duration'] = "50s"
        
        # --- Balanced local CI tuning ---
        # Run Puma in single mode to avoid cluster overhead on the
        # single-node local control plane while still allowing more
        # request concurrency than the previous 1-worker cluster setup.
        puma['worker_processes'] = 0
        puma['max_threads'] = 8
        
        # Sidekiq is the main memory spike during CI trace/artifact bursts.
        # Keep enough workers for responsive pipeline processing without
        # letting background jobs crowd Puma out of the cgroup.
        sidekiq['concurrency'] = 8
        
        # 3. Disable all side-utilities and monitoring
        prometheus_monitoring['enable'] = false
        alertmanager['enable'] = false
        gitlab_exporter['enable'] = false
        node_exporter['enable'] = false
        redis_exporter['enable'] = false
        
        # 4. Disable heavy enterprise components not needed for local CI
        gitlab_pages['enable'] = false
        mattermost['enable'] = false
        registry['enable'] = false
        
        # 5. Disable Redis persistence to save disk/IO overhead
        redis['save'] = []
        redis['appendonly'] = "no"
    ports:
      - "{http_port}:{http_port}"
      - "{ssh_port}:22"
    volumes:
      - "{cfg}:/etc/gitlab"
      - "{logs}:/var/log/gitlab"
      - "{data}:/var/opt/gitlab"
      - "{jeryu_bin}:/opt/jeryu/jeryu:ro"
    # Hard Docker limit so CI bursts cannot OOM-kill GitLab services
    mem_limit: 8g
    mem_reservation: 4g
    shm_size: "256m"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
"#,
        image = super::GITLAB_IMAGE,
        hostname = super::GITLAB_HOSTNAME,
        root_password = root_password,
        http_port = super::GITLAB_HTTP_PORT,
        ssh_port = super::GITLAB_SSH_PORT,
        vault_image = super::VAULT_IMAGE,
        vault_container = super::VAULT_CONTAINER_NAME,
        vault_port = super::VAULT_HTTP_PORT,
        vault_data = vault_data,
        vault_local_config = vault_local_config,
        cfg = cfg,
        logs = logs,
        data = data,
        jeryu_bin = jeryu_bin_path.display(),
    )
}
