//! Owner: Configuration & Templates subsystem
//! Proof: `cargo nextest run -p jeryu -- config`
//! Invariants: Defaults and templates remain deterministic, local, and safe for unattended bootstrap.
//! Embedded templates and configuration constants for jeryu.
//!
//! This module owns the docker-compose.yml template, runner config.toml
//! template, and all default values that flow through the system.

use std::path::PathBuf;

#[path = "config_paths.rs"]
mod paths;
#[path = "config_support.rs"]
mod support;

pub use paths::*;
pub use support::*;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ConfigLoadMode {
    Permissive,
    FailClosed,
}

// ---------------------------------------------------------------------------
// Docker Compose Template
// ---------------------------------------------------------------------------

pub fn render_compose(root_password: &str) -> String {
    let cfg = gitlab_config_dir().display().to_string();
    let logs = gitlab_logs_dir().display().to_string();
    let data = gitlab_data_dir().display().to_string();
    let vault_data = vault_storage_dir().display().to_string();
    let vault_local_config = yaml_block(&render_vault_local_config(), 8);
    let jeryu_bin_path = match std::env::current_exe() {
        Ok(path) => path,
        Err(_) => PathBuf::from("jeryu"),
    };

    format!(
        r#"# docker-compose.yml - Generated by jeryu bootstrap — do not edit manually
services:
  vault:
    image: {vault_image}
    container_name: {vault_container}
    restart: unless-stopped
    command: server
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_ADDR: "http://127.0.0.1:{vault_port}"
      VAULT_API_ADDR: "http://127.0.0.1:{vault_port}"
      VAULT_LOG_LEVEL: "warn"
      VAULT_LOCAL_CONFIG: |
{vault_local_config}
    ports:
      - "0.0.0.0:{vault_port}:8200"
    volumes:
      - "{vault_data}:/vault/file"
    healthcheck:
      test: ["CMD", "vault", "status"]
      interval: 10s
      timeout: 5s
      retries: 20

  gitlab:
    image: {image}
    container_name: jeryu-gitlab
    hostname: {hostname}
    restart: unless-stopped
    environment:
      GITLAB_ROOT_PASSWORD: "{root_password}"
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://{hostname}:{http_port}'
        gitlab_rails['gitlab_shell_ssh_port'] = {ssh_port}
        gitlab_workhorse['api_ci_long_polling_duration'] = "50s"
        
        # --- Balanced local CI tuning ---
        # Run Puma in single mode to avoid cluster overhead on the
        # single-node local control plane while still allowing more
        # request concurrency than the previous 1-worker cluster setup.
        puma['worker_processes'] = 0
        puma['max_threads'] = 8
        
        # Sidekiq is the main memory spike during CI trace/artifact bursts.
        # Keep enough workers for responsive pipeline processing without
        # letting background jobs crowd Puma out of the cgroup.
        sidekiq['concurrency'] = 8
        
        # 3. Disable all side-utilities and monitoring
        prometheus_monitoring['enable'] = false
        alertmanager['enable'] = false
        gitlab_exporter['enable'] = false
        node_exporter['enable'] = false
        redis_exporter['enable'] = false
        
        # 4. Disable heavy enterprise components not needed for local CI
        gitlab_pages['enable'] = false
        mattermost['enable'] = false
        registry['enable'] = false
        
        # 5. Disable Redis persistence to save disk/IO overhead
        redis['save'] = []
        redis['appendonly'] = "no"
    ports:
      - "{http_port}:{http_port}"
      - "{ssh_port}:22"
    volumes:
      - "{cfg}:/etc/gitlab"
      - "{logs}:/var/log/gitlab"
      - "{data}:/var/opt/gitlab"
      - "{jeryu_bin}:/opt/jeryu/jeryu:ro"
    # Hard Docker limit so CI bursts cannot OOM-kill GitLab services
    mem_limit: 8g
    mem_reservation: 4g
    shm_size: "256m"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
"#,
        image = GITLAB_IMAGE,
        hostname = GITLAB_HOSTNAME,
        root_password = root_password,
        http_port = GITLAB_HTTP_PORT,
        ssh_port = GITLAB_SSH_PORT,
        vault_image = VAULT_IMAGE,
        vault_container = VAULT_CONTAINER_NAME,
        vault_port = VAULT_HTTP_PORT,
        vault_data = vault_data,
        vault_local_config = vault_local_config,
        cfg = cfg,
        logs = logs,
        data = data,
        jeryu_bin = jeryu_bin_path.display(),
    )
}

// ---------------------------------------------------------------------------
// Runner config.toml Template
// ---------------------------------------------------------------------------

#[allow(clippy::too_many_arguments)] // runner config builder: each arg maps to a specific gitlab-runner TOML field
pub fn render_runner_config(
    pool_name: &str,
    manager_id: &str,
    gitlab_url: &str,
    token: &str,
    executor: &str,
    cache_dir: &str,
    concurrent: i64,
    request_concurrency: i64,
) -> String {
    let pool_cache_mount = pool_cache_mount_path(executor);
    let builds_dir = manager_builds_dir(pool_name, manager_id);
    let cargo_pre_build_script =
        crate::cargo_cache::render_runner_cargo_pre_build_script(pool_cache_mount, executor);
    let executor_block = match executor {
        "custom" => format!(
            r#"  executor = "custom"
  shell = "sh"
  pre_get_sources_script = "export SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt CARGO_HTTP_CAINFO=/etc/ssl/certs/ca-certificates.crt GIT_SSL_CAINFO=/etc/ssl/certs/ca-certificates.crt NODE_EXTRA_CA_CERTS=/etc/ssl/certs/ca-certificates.crt; mkdir -p {pool_cache_mount}"
  [runners.custom_build_dir]
    enabled = true

  [runners.custom]
    # In Phase 2, we use our own Rust binary to handle container lifecycles.
    # The 'jeryu' binary is mounted into the manager container from the host.
    config_exec = "/usr/local/bin/jeryu"
    config_args = ["exec", "config"]

    prepare_exec = "/usr/local/bin/jeryu"
    prepare_args = ["exec", "prepare"]

    run_exec = "/usr/local/bin/jeryu"
    run_args = ["exec", "run"]

    cleanup_exec = "/usr/local/bin/jeryu"
    cleanup_args = ["exec", "cleanup"]"#,
            pool_cache_mount = pool_cache_mount,
        ),
        _ => {
            let ca_cert = "/etc/ssl/certs/ca-certificates.crt";
            let privileged = if pool_name == "build" {
                "true"
            } else {
                "false"
            };
            format!(
                r#"  executor = "docker"
  pre_get_sources_script = "export SSL_CERT_FILE={ca_cert} CARGO_HTTP_CAINFO={ca_cert} GIT_SSL_CAINFO={ca_cert} NODE_EXTRA_CA_CERTS={ca_cert}; mkdir -p /cache; if [ -n \"$CI_PROJECT_DIR\" ] && [ -d \"$CI_PROJECT_DIR\" ]; then if [ -d \"$CI_PROJECT_DIR/.git\" ]; then rm -f \"$CI_PROJECT_DIR/.git/shallow.lock\" \"$CI_PROJECT_DIR/.git/index.lock\"; git -C \"$CI_PROJECT_DIR\" remote get-url origin >/dev/null 2>&1 || rm -rf \"$CI_PROJECT_DIR\"; else rm -rf \"$CI_PROJECT_DIR\"; fi; fi"
  pre_build_script = {cargo_pre_build_script:?}
  [runners.custom_build_dir]
    enabled = true

  [runners.docker]
    image = "alpine:latest"
    pull_policy = "if-not-present"
    allowed_pull_policies = ["always", "if-not-present", "never"]
    privileged = {privileged}
    volumes = ["{ca_cert}:{ca_cert}:ro", "{cache_dir}:/cache:rw"]
    extra_hosts = ["host.docker.internal:host-gateway", "gitlab.local:host-gateway"]"#
            )
        }
    };

    format!(
        r#"# Generated by jeryu — pool: {pool_name}
concurrent = {concurrent}
check_interval = 3
log_format = "json"
listen_address = "0.0.0.0:9252"
shutdown_timeout = 3600

[[runners]]
  name = "jeryu-{pool_name}"
  url = "{gitlab_url}"
  token = "{token}"
  builds_dir = "{builds_dir}"
  limit = {concurrent}
  request_concurrency = {request_concurrency}
  environment = [
    "SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt",
    "CARGO_HTTP_CAINFO=/etc/ssl/certs/ca-certificates.crt",
    "GIT_SSL_CAINFO=/etc/ssl/certs/ca-certificates.crt",
    "NODE_EXTRA_CA_CERTS=/etc/ssl/certs/ca-certificates.crt",
    "JERYU_SCCACHE_ENABLED={sccache_enabled}",
    "JERYU_SCCACHE_CACHE_SIZE={sccache_cache_size}",
    "JERYU_CARGO_INCREMENTAL=0",
    "JERYU_CARGO_CACHE=1",
    "JERYU_CARGO_CACHE_ROOT={pool_cache_mount}",
  ]
{executor_block}
"#,
        pool_name = pool_name,
        concurrent = concurrent,
        gitlab_url = gitlab_url,
        token = token,
        builds_dir = builds_dir,
        request_concurrency = request_concurrency,
        executor_block = executor_block,
        sccache_enabled = if crate::settings::get().sccache.enabled {
            "1"
        } else {
            "0"
        },
        sccache_cache_size = crate::settings::get().sccache.cache_size,
        pool_cache_mount = pool_cache_mount,
    )
}
