use anyhow::{Context, Result};
use std::collections::BTreeMap;
use std::fs;
use std::path::Path;

use super::{VaultEnv, config, random_alnum, write_restricted};

pub(crate) fn parse_env_file(path: &Path) -> Result<BTreeMap<String, String>> {
    let raw = fs::read_to_string(path).with_context(|| format!("read {}", path.display()))?;
    Ok(parse_env_str(&raw))
}

pub(crate) fn parse_env_str(raw: &str) -> BTreeMap<String, String> {
    let mut out = BTreeMap::new();
    for line in raw.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let Some((key, value)) = line.split_once('=') else {
            continue;
        };
        out.insert(
            key.trim().to_string(),
            value
                .trim()
                .trim_matches('"')
                .trim_matches('\'')
                .to_string(),
        );
    }
    out
}

pub(crate) fn write_env_map(path: &Path, values: &BTreeMap<String, String>) -> Result<()> {
    let body = values
        .iter()
        .map(|(key, value)| format!("{key}={value}"))
        .collect::<Vec<_>>()
        .join("\n");
    write_restricted(path, &format!("{body}\n"))
}

pub(crate) fn ensure_jeryu_compose_inputs() -> Result<String> {
    let env_path = config::env_file();
    if !env_path.exists() {
        let root_password = random_alnum(24);
        let webhook_secret = random_alnum(32);
        let body = format!(
            "# Generated by jeryu secrets provision - do not share\n\
             GITLAB_ROOT_PASSWORD={root_password}\n\
             JERYU_WEBHOOK_SECRET={webhook_secret}\n"
        );
        write_restricted(&env_path, &body)?;
        return Ok(root_password);
    }
    let parsed = parse_env_file(&env_path)?;
    if let Some(root_password) = parsed.get("GITLAB_ROOT_PASSWORD").cloned() {
        return Ok(root_password);
    }
    let root_password = random_alnum(24);
    let webhook_secret = match parsed.get("JERYU_WEBHOOK_SECRET").cloned() {
        Some(value) => value,
        None => random_alnum(32),
    };
    let body = format!(
        "# Generated by jeryu secrets provision - do not share\n\
         GITLAB_ROOT_PASSWORD={root_password}\n\
         JERYU_WEBHOOK_SECRET={webhook_secret}\n"
    );
    write_restricted(&env_path, &body)?;
    Ok(root_password)
}

pub(crate) fn load_vault_env() -> Result<Option<VaultEnv>> {
    let path = config::vault_env_file();
    if !path.exists() {
        return Ok(None);
    }
    let parsed = parse_env_file(&path)?;
    let Some(addr) = parsed.get("JERYU_VAULT_ADDR").cloned() else {
        return Ok(None);
    };
    let Some(token) = parsed.get("JERYU_VAULT_TOKEN").cloned() else {
        return Ok(None);
    };
    Ok(Some(VaultEnv {
        addr,
        token,
        mount: match parsed.get("JERYU_VAULT_MOUNT").cloned() {
            Some(value) => value,
            None => config::VAULT_DEFAULT_MOUNT.to_string(),
        },
        prefix: match parsed.get("JERYU_VAULT_PREFIX").cloned() {
            Some(value) => value,
            None => config::VAULT_DEFAULT_PREFIX.to_string(),
        },
    }))
}

pub(crate) fn save_vault_env(env: &VaultEnv) -> Result<()> {
    let mut values = BTreeMap::new();
    values.insert("JERYU_VAULT_ADDR".to_string(), env.addr.clone());
    values.insert("JERYU_VAULT_TOKEN".to_string(), env.token.clone());
    values.insert("JERYU_VAULT_MOUNT".to_string(), env.mount.clone());
    values.insert("JERYU_VAULT_PREFIX".to_string(), env.prefix.clone());
    write_env_map(&config::vault_env_file(), &values)
}
