//! Owner: CI Test Runner subsystem
//! Proof: `cargo nextest run -p jeryu -- test_runner`
//! Invariants: Test execution preserves lane semantics and reports enough structure for VTI feedback.
//! Test Runner: Agent-friendly single-test execution via jeryu.
//!
//! Enables an agent to run a single test (or set of tests) through the
//! GitLab CI pipeline and get structured results back. Works by creating
//! a dynamic pipeline with just the requested test command.

use crate::release;
use anyhow::Result;
use serde::{Deserialize, Serialize};

// ---------------------------------------------------------------------------
// Public types
// ---------------------------------------------------------------------------

/// Result of a test run through the CI pipeline.
#[derive(Debug, Serialize, Deserialize)]
pub struct TestRunResult {
    pub pipeline_id: i64,
    pub job_id: Option<i64>,
    pub job_name: String,
    pub status: String,
    pub duration_secs: Option<f64>,
    pub trace_tail: String,
    pub passed: bool,
}

/// Planning metadata for a test run.
#[derive(Debug, Serialize, Deserialize)]
pub struct TestRunPlan {
    pub command: String,
    pub job_name: String,
    pub image: String,
    pub tags: Vec<String>,
    pub timeout_secs: u64,
    pub risk_class: String,
    pub rationale: Vec<String>,
}

/// Options for running a test.
#[derive(Debug, Clone)]
pub struct TestRunOpts {
    pub project_id: i64,
    pub test_command: String,
    pub job_name: Option<String>,
    pub image: String,
    pub tags: Option<Vec<String>>,
    pub timeout_secs: u64,
    pub force: bool,
    pub commit_sha: String,
}

impl Default for TestRunOpts {
    fn default() -> Self {
        Self {
            project_id: release::DEFAULT_RELEASE_PROJECT_ID,
            test_command: String::new(),
            job_name: None,
            image: "rust:1.92.0".to_string(),
            tags: None,
            timeout_secs: 600,
            force: false,
            commit_sha: "latest".to_string(),
        }
    }
}

/// Options for running multiple tests in parallel through CI pipelines.
#[derive(Debug, Clone)]
pub struct TestBatchOpts {
    pub project_id: i64,
    pub test_commands: Vec<String>,
    pub job_name_prefix: Option<String>,
    pub image: String,
    pub tags: Option<Vec<String>>,
    pub timeout_secs: u64,
    pub max_parallel: usize,
    pub force: bool,
    pub commit_sha: String,
}

impl Default for TestBatchOpts {
    fn default() -> Self {
        Self {
            project_id: release::DEFAULT_RELEASE_PROJECT_ID,
            test_commands: Vec::new(),
            job_name_prefix: None,
            image: "rust:1.92.0".to_string(),
            tags: None,
            timeout_secs: 600,
            max_parallel: 3,
            force: false,
            commit_sha: "latest".to_string(),
        }
    }
}

// ---------------------------------------------------------------------------
// Core API
// ---------------------------------------------------------------------------

pub fn plan_test_run(opts: &TestRunOpts) -> TestRunPlan {
    let job_name = match opts.job_name.clone() {
        Some(value) => value,
        None => "jeryu-test-run".to_string(),
    };
    let inferred = match opts.tags.clone() {
        Some(value) => value,
        None => routing::infer_test_tags(&opts.test_command),
    };
    let routing = routing::infer_test_routing(&opts.test_command);
    let timeout_secs = if opts.timeout_secs == TestRunOpts::default().timeout_secs {
        routing.timeout_secs
    } else {
        opts.timeout_secs
    };

    TestRunPlan {
        command: opts.test_command.clone(),
        job_name,
        image: opts.image.clone(),
        tags: inferred,
        timeout_secs,
        risk_class: routing.risk_class,
        rationale: routing.rationale,
    }
}

pub(crate) fn render_ephemeral_ci_yaml(plan: &TestRunPlan) -> String {
    format!(
        r#"# Auto-generated by jeryu test run — ephemeral pipeline
{job_name}:
  stage: test
  image: {image}
  variables:
    GIT_STRATEGY: clone
    GIT_CLONE_PATH: "$CI_BUILDS_DIR/$CI_PROJECT_PATH_SLUG-jeryu-$CI_PIPELINE_ID-$CI_JOB_ID"
  script:
    - {command}
"#,
        job_name = plan.job_name,
        image = plan.image,
        command = plan.command,
    )
}

#[path = "test_runner_routing.rs"]
mod routing;

#[path = "test_runner_runtime.rs"]
mod runtime;
pub async fn run_test(
    db: &crate::state::Db,
    client: &crate::gitlab_client::GitlabClient,
    opts: &TestRunOpts,
) -> Result<TestRunResult> {
    runtime::run_test(db, client, opts).await
}

pub(crate) async fn wait_for_test_result(
    client: &crate::gitlab_client::GitlabClient,
    project_id: i64,
    pipeline_id: i64,
    job_name: &str,
    timeout_secs: u64,
) -> Result<TestRunResult> {
    runtime::wait_for_test_result(client, project_id, pipeline_id, job_name, timeout_secs).await
}

#[path = "test_runner_job_ops.rs"]
mod job_ops;
pub async fn run_test_batch(
    db: &crate::state::Db,
    client: &crate::gitlab_client::GitlabClient,
    opts: &TestBatchOpts,
) -> Result<Vec<TestRunResult>> {
    job_ops::run_test_batch(db, client, opts).await
}

pub async fn requeue_job_by_name(
    client: &crate::gitlab_client::GitlabClient,
    project_id: i64,
    pipeline_id: i64,
    job_name: &str,
) -> Result<TestRunResult> {
    job_ops::requeue_job_by_name(client, project_id, pipeline_id, job_name).await
}

pub async fn pipeline_results(
    client: &crate::gitlab_client::GitlabClient,
    project_id: i64,
    pipeline_id: i64,
) -> Result<Vec<TestRunResult>> {
    job_ops::pipeline_results(client, project_id, pipeline_id).await
}

#[cfg(test)]
#[path = "test_runner_tests.rs"]
mod tests;
